using System;
using System.Collections.Generic;
using NUnit.Framework;
using Spotlight.Contracts;
using Spotlight.Core;
using Spotlight.Core.Flow;
using Spotlight.Core.Events;
namespace Spotlight.Tests.Integration {
public sealed class FlowIntegrationTests {
 Harness h;GameFlowService flow;CoreServices core;Catalog catalog;
 [SetUp]public void Setup(){catalog=new Catalog();var events=new GameEventBus();core=new CoreServices(catalog,events);h=new Harness(core);flow=new GameFlowService(core,catalog,h,h,h,h,h,h,h,h,h,h,h,events,new ISessionModule[0]);}
 CommandContext Command(){return core.Commands.Create(core.Transactions.Revision);}
 void New(GameMode mode){Assert.AreEqual(OperationState.Committed,flow.TryNewRun(Command(),new NewRunRequest{LevelId="level",Mode=mode,Seed=5}).State);}
 void Complete(){h.Complete=true;flow.Tick(new TickContext(1,1,1f/30,TickStage.Outcome));}
 void SetDay(int day,GameMode mode){var data=core.Store.CaptureCheckpoint(catalog);data.Mode=mode;data.DayIndex=day;data.LastSettledNight=day-1;data.DayEvent=new DayEventState{DayIndex=day,InstanceId="saved",Resolved=true};Assert.AreEqual(OperationState.Committed,flow.TryReturnToMenu(Command()).State);Assert.AreEqual(OperationState.Committed,flow.TryLoadRun(Command(),data).State);}
 [Test]public void FirstDayDoesNotProduceAndRepeatedConfirmProducesExactlyOnce(){New(GameMode.Story);Assert.AreEqual(GamePhase.Build,flow.GetSnapshot().Phase);Assert.AreEqual(0,h.Productions);Assert.AreEqual(OperationState.Committed,flow.TryStartNight(Command()).State);Complete();var command=Command();var first=flow.TryConfirmNightResult(command);Assert.AreEqual(OperationState.Committed,first.State);Assert.AreEqual(first.Revision,flow.TryConfirmNightResult(command).Revision);Assert.AreEqual(2,flow.GetSnapshot().DayIndex);Assert.AreEqual(1,h.Productions);Assert.AreEqual(1,core.Resources.GetQuantity(ResourceBucket.Hand,"water"));}
 [Test]public void FailedProductionLeavesNightResultDayResourcesAndRandomUntouched(){New(GameMode.Story);flow.TryStartNight(Command());Complete();var before=core.Random.GetState(RandomStream.Production);h.BadProduction=true;Assert.AreEqual(OperationState.Rejected,flow.TryConfirmNightResult(Command()).State);Assert.AreEqual(GamePhase.NightResult,flow.GetSnapshot().Phase);Assert.AreEqual(1,flow.GetSnapshot().DayIndex);Assert.AreEqual(0,core.Resources.GetQuantity(ResourceBucket.Hand,"water"));Assert.AreEqual(before.State,core.Random.GetState(RandomStream.Production).State);h.BadProduction=false;Assert.AreEqual(OperationState.Committed,flow.TryConfirmNightResult(Command()).State);Assert.AreEqual(2,flow.GetSnapshot().DayIndex);} [Test]public void NightRejectsFreshNewAndLoadButOriginalSuccessfulCommandRetryIsSafe(){var original=Command();var request=new NewRunRequest{LevelId="level",Mode=GameMode.Story,Seed=5};var created=flow.TryNewRun(original,request);var data=core.Store.CaptureCheckpoint(catalog);flow.TryStartNight(Command());Assert.AreEqual(ErrorCode.WrongPhase,flow.TryNewRun(Command(),request).Error);Assert.AreEqual(ErrorCode.WrongPhase,flow.TryLoadRun(Command(),data).Error);Assert.AreEqual(created.Revision,flow.TryNewRun(original,request).Revision);Assert.AreEqual(GamePhase.Night,flow.GetSnapshot().Phase);Assert.AreEqual(ErrorCode.DuplicateCommand,flow.TryNewRun(original,new NewRunRequest{LevelId="level",Mode=GameMode.Story,Seed=6}).Error);}
 [Test]public void FlowCommandIdCannotReuseAnExistingTransactionBody(){New(GameMode.Story);var command=Command();core.Transactions.TryCommit(new StateMutationBatch{Context=command,ResourceDeltas=new[]{new ResourceAmount(ResourceBucket.Hand,"water",1)}});Assert.AreEqual(ErrorCode.DuplicateCommand,flow.TryDismissTutorial(command).Error);Assert.IsFalse(flow.GetSnapshot().TutorialShown);} [Test]public void DaytimeDeathImmediatelyPreventsNight(){New(GameMode.Story);core.Transactions.TryCommit(new StateMutationBatch{Context=Command(),Actors=new[]{new ActorMutation{ActorId=core.World.SpringId,Kind=ActorMutationKind.SetHealth,CurrentHp=0,MaxHp=100}}});flow.SynchronizeDayEvent();Assert.AreEqual(GamePhase.GameOver,flow.GetSnapshot().Phase);Assert.AreEqual(ErrorCode.WrongPhase,flow.TryStartNight(Command()).Error);}
 [Test]public void BossAndSpringDeathSameTickLosesAndPendingDamagePreventsWin(){New(GameMode.Story);SetDay(7,GameMode.Story);flow.TryStartNight(Command());h.FinalBossKilled=true;h.Pending=1;Complete();Assert.AreEqual(GamePhase.Night,flow.GetSnapshot().Phase);core.Transactions.TryCommit(new StateMutationBatch{Context=Command(),Actors=new[]{new ActorMutation{ActorId=core.World.SpringId,Kind=ActorMutationKind.SetHealth,CurrentHp=0,MaxHp=100}}});Complete();Assert.AreEqual(GamePhase.GameOver,flow.GetSnapshot().Phase);}
 [Test]public void Endless50Continues51AndGrantsMilestoneOnce(){New(GameMode.Endless);SetDay(50,GameMode.Endless);flow.TryStartNight(Command());Complete();Assert.AreEqual(ErrorCode.EventUnresolved,flow.TryConfirmNightResult(Command()).Error);var c=Command();Assert.AreEqual(OperationState.Committed,flow.TryContinueEndless(c).State);Assert.AreEqual(OperationState.Committed,flow.TryContinueEndless(c).State);Assert.AreEqual(51,flow.GetSnapshot().DayIndex);Assert.IsTrue(flow.GetSnapshot().Milestone50Claimed);Assert.AreEqual(11,core.Resources.GetQuantity(ResourceBucket.Hand,"water"));}
 [Test]public void LoadDoesNotDrawEventOrProduceAndNightSaveFailureKeepsBuild(){New(GameMode.Story);var data=core.Store.CaptureCheckpoint(catalog);int draws=h.Events,production=h.Productions;Assert.AreEqual(OperationState.Committed,flow.TryReturnToMenu(Command()).State);Assert.AreEqual(OperationState.Committed,flow.TryLoadRun(Command(),data).State);Assert.AreEqual(draws,h.Events);Assert.AreEqual(production,h.Productions);h.SaveFails=true;Assert.AreEqual(ErrorCode.SaveIoFailure,flow.TryStartNight(Command()).Error);Assert.AreEqual(GamePhase.Build,flow.GetSnapshot().Phase);}
 sealed class TraceModule:ISessionModule { readonly int index;readonly List<int> ended;public TraceModule(int index,List<int> ended){this.index=index;this.ended=ended;}public ModuleId Module{get{return ModuleId.Combat;}}public void BeginSession(SessionStartContext c){}public void EndSession(){ended.Add(index);}}
 [Test]public void SessionModulesEndInReverseOrder(){var order=new List<int>();flow=new GameFlowService(core,catalog,h,h,h,h,h,h,h,h,h,h,h,new GameEventBus(),new ISessionModule[]{new TraceModule(1,order),new TraceModule(2,order),new TraceModule(3,order)});New(GameMode.Story);order.Clear();Assert.AreEqual(OperationState.Committed,flow.TryReturnToMenu(Command()).State);Assert.AreEqual(3,order.Count);Assert.AreEqual(3,order[0]);Assert.AreEqual(2,order[1]);Assert.AreEqual(1,order[2]);} sealed class Harness:IElementRuleService,ISaveService,IWaveService,IDamageService,ISpecialSkillService,ITowerService,IProjectileService,IItemService,IDayEventService,IGameClock,ISimulationDriver {
  readonly CoreServices core;public int Productions,Events,Pending;public bool Complete,FinalBossKilled,SaveFails,BadProduction;public Harness(CoreServices c){core=c;}
  OperationResult Ok(){return new OperationResult(OperationState.Committed,ErrorCode.None,Guid.NewGuid(),core.Transactions.Revision,null);}
  public ProductionResult ResolveProduction(ProductionInput i){Productions++;return new ProductionResult{SettlementId=i.SettlementId,ExpectedRevision=i.Board.Revision,CompletedNight=i.CompletedNight,Board=new BoardMutation[0],HandDeltas=new[]{new ResourceAmount(ResourceBucket.Hand,"water",BadProduction?-1:1)},NextRandom=i.Random};}public ReactionPlan ResolveReactions(ReactionInput i){throw new NotSupportedException();}public ProjectileModifierDefinition GetProjectileModifier(ElementType e){throw new NotSupportedException();}
  public bool HasCheckpoint{get{return false;}}public OperationResult SaveCheckpoint(CommandContext c,SaveReason r){return SaveFails?new OperationResult(OperationState.Rejected,ErrorCode.SaveIoFailure,c.CommandId,core.Transactions.Revision,null):Ok();}public SaveReadResult ReadCheckpoint(){throw new NotSupportedException();}
  WaveSnapshot IWaveService.GetSnapshot(){return new WaveSnapshot{Complete=Complete,FinalBossKilled=FinalBossKilled};}public OperationResult StartNight(int day,GameMode mode){Complete=false;FinalBossKilled=false;return Ok();}public OperationResult ScheduleSummons(EntityId owner,IReadOnlyList<SpawnGroupDefinition> groups){throw new NotSupportedException();}public void CancelSummons(EntityId owner){}public void Stop(){}
  public int PendingCount{get{return Pending;}}public OperationResult Enqueue(DamagePacket p){throw new NotSupportedException();}public DamageResult Preview(DamagePacket p){throw new NotSupportedException();}
  SpecialSkillSnapshot ISpecialSkillService.GetSnapshot(){return new SpecialSkillSnapshot();}public OperationResult TryUse(CommandContext c){throw new NotSupportedException();}public void ResetForNight(){}
  public IReadOnlyList<ActorSnapshot> GetTowers(){return new ActorSnapshot[0];}public void SynchronizeBoard(){}public void ResetNightCooldowns(){}
  public OperationResult Spawn(ProjectileSpawnRequest p){throw new NotSupportedException();}IReadOnlyList<ProjectileSnapshot> IProjectileService.GetSnapshot(){return new ProjectileSnapshot[0];}public void Clear(){}
  public ValidationResult CheckUse(ItemUseRequest r){throw new NotSupportedException();}public OperationResult TryUse(CommandContext c,ItemUseRequest r){throw new NotSupportedException();}public IReadOnlyList<ItemGroupSnapshot> GetActiveGroups(){return new ItemGroupSnapshot[0];}public void ResetTransient(){}
  DayEventSnapshot IDayEventService.GetSnapshot(){return new DayEventSnapshot{State=core.Store.GetDayEventState()};}public OperationResult EnsureEvent(int day,GameMode mode){Events++;return core.Transactions.TryCommit(new StateMutationBatch{Context=core.Commands.Create(core.Transactions.Revision),DayEvent=new DayEventState{DayIndex=day,InstanceId="event"+day,Resolved=true}});}public OperationResult TryChoose(CommandContext c,string instance,string option){throw new NotSupportedException();}
  ClockSnapshot IGameClock.GetSnapshot(){return new ClockSnapshot{Reasons=new PauseReason[0]};}public OperationResult TrySetSpeed(CommandContext c,GameSpeed speed){throw new NotSupportedException();}public Guid AcquirePause(PauseReason p){return Guid.NewGuid();}public void ReleasePause(Guid id){}public void Register(ITickSystem t){}public void Advance(float delta){}public void Reset(){}
 }
 sealed class Catalog:IGameCatalog {
  public GameSettings GetSettings(){return new GameSettings{ConfigVersion="flow",StoryDays=7,SpringMaxHp=100};}public bool TryGetLevel(string id,out LevelDefinition v){v=new LevelDefinition{Id="level",Rows=3,Columns=3,CellSize=1,SpringCell=new CellCoord(0,0),SpawnPoints=new SpawnPointDefinition[0],Paths=new PathDefinition[0],InitialOccupants=new InitialOccupant[0],InitialResources=new ResourceAmount[0],ReservedCells=new CellCoord[0]};return id=="level";}public bool TryGetElement(string id,out ElementDefinition v){v=new ElementDefinition{Id="water"};return id=="water";}
  public bool TryGetTower(string id,out TowerDefinition v){v=null;return false;}public bool TryGetProjectile(string id,out ProjectileDefinition v){v=null;return false;}public bool TryGetStatus(string id,out StatusDefinition v){v=null;return false;}public bool TryGetEnemy(string id,out EnemyDefinition v){v=null;return false;}public bool TryGetItem(string id,out ItemDefinition v){v=null;return false;}public bool TryGetResource(string id,out ResourceDefinition v){v=null;return false;}public bool TryGetEvent(string id,out DayEventDefinition v){v=null;return false;}public bool TryGetBossSkill(string id,out BossSkillDefinition v){v=null;return false;}public bool TryGetDropTable(string id,out DropTableDefinition v){v=null;return false;}public bool TryGetSkill(string id,out SpecialSkillDefinition v){v=null;return false;}public EndlessDefinition GetEndlessDefinition(){return new EndlessDefinition{MilestoneNight=50,MilestoneRewards=new[]{new ResourceAmount(ResourceBucket.Hand,"water",10)}};}public IReadOnlyList<ProductionRuleDefinition> GetProductionRules(){return new ProductionRuleDefinition[0];}public IReadOnlyList<ReactionDefinition> GetReactionRules(ReactionContext c){return new ReactionDefinition[0];}public IReadOnlyList<GaugeDefinition> GetGaugeDefinitions(){return new GaugeDefinition[0];}public IReadOnlyList<DayEventDefinition> GetDayEvents(){return new DayEventDefinition[0];}public IReadOnlyList<WaveDefinition> GetWaves(int d,GameMode m){return new WaveDefinition[0];}public IReadOnlyList<string> ValidateAll(){return new string[0];}
 }
}
}



