using System;
using System.IO;
using System.Text;
using System.Collections.Generic;
using Spotlight.Contracts;
namespace Spotlight.Core.Save {
public sealed class SaveService : ISaveService {
 readonly SessionStateStore store;readonly IGameCatalog catalog;readonly IEventBus events;readonly string directory;readonly Func<CheckpointFileModel,string> encode;readonly Func<string,CheckpointFileModel> decode;bool busy;readonly Dictionary<CheckpointData,CommandHistoryRecord[]> histories=new Dictionary<CheckpointData,CommandHistoryRecord[]>();
 public SaveService(SessionStateStore store,IGameCatalog catalog,IEventBus events,string directory):this(store,catalog,events,directory,delegate(CheckpointFileModel m){return UnityEngine.JsonUtility.ToJson(m,true);},delegate(string json){return UnityEngine.JsonUtility.FromJson<CheckpointFileModel>(json);}){}
 public SaveService(SessionStateStore store,IGameCatalog catalog,IEventBus events,string directory,Func<CheckpointFileModel,string> encode,Func<string,CheckpointFileModel> decode){if(store==null||catalog==null||string.IsNullOrEmpty(directory)||encode==null||decode==null)throw new ArgumentException("save.dependencies.invalid");this.store=store;this.catalog=catalog;this.events=events;this.directory=Path.GetFullPath(directory);this.encode=encode;this.decode=decode;}
 string MainPath{get{return Path.Combine(directory,"checkpoint.json");}}string BackupPath{get{return Path.Combine(directory,"checkpoint.bak");}}string TempPath{get{return Path.Combine(directory,"checkpoint.tmp");}}
 public bool HasCheckpoint{get{return File.Exists(MainPath)||File.Exists(BackupPath);}}
 OperationResult Fail(CommandContext c,ErrorCode error,string key){if(events!=null)events.Publish(new SaveFailedEvent{Error=error,MessageKey=key});return new OperationResult(OperationState.Rejected,error,c.CommandId,store.GetFlowSnapshot().Revision,key);}
 public OperationResult SaveCheckpoint(CommandContext context,SaveReason reason){var f=store.GetFlowSnapshot();string fingerprint="save:"+(int)reason+":"+context.RunId+":"+context.ExpectedRevision;CommandHistoryRecord prior;if(store.TryGetCommandHistory(context.CommandId,out prior))return prior.Fingerprint==fingerprint?new OperationResult(prior.State,prior.Error,context.CommandId,prior.Revision,prior.MessageKey):Fail(context,ErrorCode.DuplicateCommand,"save.command.conflict");if(context.CommandId==Guid.Empty)return Fail(context,ErrorCode.InvalidArgument,"save.command.empty");if(busy)return Fail(context,ErrorCode.SaveBusy,"save.busy");if(context.RunId!=f.RunId)return Fail(context,ErrorCode.WrongRun,"save.run");if(context.ExpectedRevision>=0&&context.ExpectedRevision!=f.Revision)return Fail(context,ErrorCode.VersionConflict,"save.revision");if(f.Phase!=GamePhase.Build||!f.CanStartNight)return Fail(context,ErrorCode.SaveUnavailable,"save.requires.stable.build");busy=true;
  try{var checkpoint=store.CaptureCheckpoint(catalog);var valid=Validate(checkpoint);if(valid.Error!=ErrorCode.None)return Fail(context,valid.Error,valid.MessageKey);Directory.CreateDirectory(directory);var receipt=new CommandHistoryRecord{CommandId=context.CommandId.ToString("N"),Fingerprint=fingerprint,State=OperationState.Committed,Error=ErrorCode.None,Revision=f.Revision};var ids=new List<Guid>(checkpoint.CommittedCommandIds);ids.Add(context.CommandId);checkpoint.CommittedCommandIds=ids.ToArray();var history=new List<CommandHistoryRecord>(store.ExportCommandHistory());history.Add(receipt);var wire=CheckpointFileModel.FromCheckpoint(checkpoint);wire.CommandHistory=history.ToArray();string json=encode(wire);if(string.IsNullOrEmpty(json))return Fail(context,ErrorCode.SaveIoFailure,"save.codec.empty");
   using(var stream=new FileStream(TempPath,FileMode.Create,FileAccess.Write,FileShare.None)){var bytes=new UTF8Encoding(false,true).GetBytes(json);stream.Write(bytes,0,bytes.Length);stream.Flush(true);}
   var readBack=ReadOne(TempPath);if(readBack.Error!=ErrorCode.None)return Fail(context,readBack.Error,"save.readback.invalid:"+readBack.MessageKey);if(!Same(checkpoint,readBack.Data))return Fail(context,ErrorCode.SaveCorrupt,"save.readback.mismatch");
   if(File.Exists(MainPath)){var old=ReadOne(MainPath);if(old.Error==ErrorCode.None)File.Replace(TempPath,MainPath,BackupPath);else File.Replace(TempPath,MainPath,null);}else File.Move(TempPath,MainPath);
   var recorded=store.RecordCommandHistory(receipt);if(recorded.Error!=ErrorCode.None)return Fail(context,recorded.Error,"save.history.record.failure");if(events!=null)events.Publish(new CheckpointSavedEvent{Reason=reason,Revision=f.Revision});return new OperationResult(OperationState.Committed,ErrorCode.None,context.CommandId,f.Revision,null);
  }catch(UnauthorizedAccessException){return Fail(context,ErrorCode.SaveIoFailure,"save.access.denied");}catch(IOException){return Fail(context,ErrorCode.SaveIoFailure,"save.io.failure");}catch(Exception){return Fail(context,ErrorCode.SaveIoFailure,"save.write.failure");}finally{busy=false;}
 }
 public ValidationResult RestoreHistoryFor(CheckpointData data){CommandHistoryRecord[] history;if(data==null)return new ValidationResult(ErrorCode.SaveCorrupt,"save.history.null");if(!histories.TryGetValue(data,out history))return new ValidationResult(ErrorCode.None,null);return store.RestoreCommandHistory(history);} bool Same(CheckpointData a,CheckpointData b){return encode(CheckpointFileModel.FromCheckpoint(a))==encode(CheckpointFileModel.FromCheckpoint(b));}
 public SaveReadResult ReadCheckpoint(){if(busy)return new SaveReadResult{Error=ErrorCode.SaveBusy,MessageKey="save.busy"};var main=ReadOne(MainPath,true);if(main.Error==ErrorCode.None)return main;var backup=ReadOne(BackupPath,true);if(backup.Error==ErrorCode.None){backup.UsedBackup=true;return backup;}return main.Error==ErrorCode.SaveUnavailable?backup:main;}
 SaveReadResult ReadOne(string path,bool remember=false){try{if(!File.Exists(path))return new SaveReadResult{Error=ErrorCode.SaveUnavailable,MessageKey="save.not.found"};string json=File.ReadAllText(path,new UTF8Encoding(false,true));if(string.IsNullOrWhiteSpace(json))return new SaveReadResult{Error=ErrorCode.SaveCorrupt,MessageKey="save.empty"};var model=decode(json);if(model==null)return new SaveReadResult{Error=ErrorCode.SaveCorrupt,MessageKey="save.json.invalid"};if(model.SaveVersion!=1||model.ContractVersion!=ContractVersion.Value)return new SaveReadResult{Error=ErrorCode.SaveVersionUnsupported,MessageKey="save.version.unsupported"};if(model.ConfigVersion!=catalog.GetSettings().ConfigVersion)return new SaveReadResult{Error=ErrorCode.ConfigMismatch,MessageKey="save.config.mismatch"};var data=model.ToCheckpoint();var valid=Validate(data);if(valid.Error==ErrorCode.None&&model.CommandHistory!=null){var validationStore=new SessionStateStore(catalog);valid=validationStore.Restore(data);if(valid.Error==ErrorCode.None)valid=validationStore.RestoreCommandHistory(model.CommandHistory);if(valid.Error==ErrorCode.None){var expected=new HashSet<Guid>(data.CommittedCommandIds);if(expected.Count!=model.CommandHistory.Length)valid=new ValidationResult(ErrorCode.SaveCorrupt,"save.history.ids");else foreach(var record in model.CommandHistory){Guid id;if(!Guid.TryParse(record.CommandId,out id)||!expected.Remove(id)){valid=new ValidationResult(ErrorCode.SaveCorrupt,"save.history.ids");break;}}}if(valid.Error==ErrorCode.None&&remember){if(histories.Count>=8)histories.Clear();histories[data]=model.CommandHistory;}}return new SaveReadResult{Error=valid.Error,MessageKey=valid.MessageKey,Data=valid.Error==ErrorCode.None?data:null};}catch(UnauthorizedAccessException){return new SaveReadResult{Error=ErrorCode.SaveIoFailure,MessageKey="save.access.denied"};}catch(IOException){return new SaveReadResult{Error=ErrorCode.SaveIoFailure,MessageKey="save.io.failure"};}catch(Exception){return new SaveReadResult{Error=ErrorCode.SaveCorrupt,MessageKey="save.format.invalid"};}}
 ValidationResult Validate(CheckpointData data){if(data.SaveVersion!=1||data.ContractVersion!=ContractVersion.Value)return new ValidationResult(ErrorCode.SaveVersionUnsupported,"save.version.unsupported");if(data.ConfigVersion!=catalog.GetSettings().ConfigVersion)return new ValidationResult(ErrorCode.ConfigMismatch,"save.config.mismatch");LevelDefinition level;if(!catalog.TryGetLevel(data.LevelId,out level))return new ValidationResult(ErrorCode.InvalidDefinition,"save.level.missing");if(!Enum.IsDefined(typeof(GameMode),data.Mode)||!Finite(data.SpringHp)||!Finite(data.SpringMaxHp)||data.SpringHp<=0||data.SpringMaxHp<=0||data.SpringHp>data.SpringMaxHp)return new ValidationResult(ErrorCode.SaveCorrupt,"save.spring.invalid");if(data.Mode==GameMode.Story&&data.DayIndex>catalog.GetSettings().StoryDays)return new ValidationResult(ErrorCode.SaveCorrupt,"save.day.invalid");if(data.DayEvent!=null&&(data.DayEvent.DayIndex!=data.DayIndex||!data.DayEvent.Resolved||string.IsNullOrEmpty(data.DayEvent.InstanceId)))return new ValidationResult(ErrorCode.SaveCorrupt,"save.event.invalid");
  if(data.DayEvent!=null&&!string.IsNullOrEmpty(data.DayEvent.DefinitionId)){DayEventDefinition definition;if(!catalog.TryGetEvent(data.DayEvent.DefinitionId,out definition))return new ValidationResult(ErrorCode.InvalidDefinition,"save.event.missing");bool option=false;if(definition.Options!=null)foreach(var o in definition.Options)if(o.Id==data.DayEvent.ChosenOptionId)option=true;if(!option)return new ValidationResult(ErrorCode.SaveCorrupt,"save.event.option.invalid");}
  var ids=new HashSet<long>();ids.Add(data.SpringId.Value);foreach(var o in data.Occupants){if(!ids.Add(o.Id.Value)||!Finite(o.CurrentHp)||!Finite(o.MaxHp)||o.CurrentHp<0||o.MaxHp<0||o.CurrentHp>o.MaxHp)return new ValidationResult(ErrorCode.SaveCorrupt,"save.occupant.invalid");TowerDefinition tower;ElementDefinition element;if(o.Kind==OccupantKind.Tower){if(!catalog.TryGetTower(o.DefinitionId,out tower))return new ValidationResult(ErrorCode.InvalidDefinition,"save.tower.missing");if(o.AttackStacks<1||o.AttackStacks>tower.MaxAttackStacks)return new ValidationResult(ErrorCode.SaveCorrupt,"save.tower.stacks.invalid");}else if(o.Kind==OccupantKind.ElementBlock){if(!catalog.TryGetElement(o.DefinitionId,out element))return new ValidationResult(ErrorCode.InvalidDefinition,"save.element.missing");}else return new ValidationResult(ErrorCode.SaveCorrupt,"save.occupant.kind.invalid");}
  foreach(var r in data.Resources){ElementDefinition element;ItemDefinition item;ResourceDefinition resource;bool valid=r.Bucket==ResourceBucket.Hand?catalog.TryGetElement(r.DefinitionId,out element):r.Bucket==ResourceBucket.Inventory&&(catalog.TryGetItem(r.DefinitionId,out item)||catalog.TryGetResource(r.DefinitionId,out resource));if(!valid)return new ValidationResult(ErrorCode.InvalidDefinition,"save.resource.missing");if(r.Amount<0)return new ValidationResult(ErrorCode.SaveCorrupt,"save.resource.negative");}return store.ValidateCheckpoint(data);
 }
 static bool Finite(float value){return !float.IsNaN(value)&&!float.IsInfinity(value);}
}
}





