using System;
using System.Collections.Generic;
using Spotlight.Contracts;
namespace Spotlight.Core
{
    public sealed class SessionStateStore
    {
        internal readonly IGameCatalog Catalog;
        internal FlowSnapshot Progress = new FlowSnapshot { Phase = GamePhase.Menu };
        internal Dictionary<CellCoord,CellSnapshot> Cells = new Dictionary<CellCoord,CellSnapshot>();
        internal Dictionary<long,ActorSnapshot> Actors = new Dictionary<long,ActorSnapshot>();
        internal Dictionary<string,long> Quantities = new Dictionary<string,long>();
        internal Dictionary<RandomStream,uint> RandomStates = new Dictionary<RandomStream,uint>();
        internal Dictionary<Guid,string> Fingerprints = new Dictionary<Guid,string>();
        internal Dictionary<Guid,OperationResult> Results = new Dictionary<Guid,OperationResult>();
        internal Dictionary<Guid,string> DeploymentRequests = new Dictionary<Guid,string>();
        internal DayEventState Event;
        internal LevelDefinition ActiveLevel;
        public LevelDefinition Level { get { return Spotlight.Core.Data.DtoCopy.Clone(ActiveLevel); } private set { ActiveLevel=value; } }
        public EntityId SpringId { get; private set; }
        public uint RunSeed { get; private set; }
        public long NextEntityId { get; internal set; }
        public long NextSpawnSequence { get; internal set; }
        public SessionStateStore(IGameCatalog catalog) { Catalog=catalog; Reset(); }
        public void Reset() { Progress=new FlowSnapshot { Phase=GamePhase.Menu }; Cells.Clear(); Actors.Clear(); Quantities.Clear(); RandomStates.Clear(); Fingerprints.Clear(); Results.Clear(); DeploymentRequests.Clear(); Event=null; Level=null; SpringId=new EntityId(0); NextEntityId=1; NextSpawnSequence=1; }
        internal static string Key(ResourceBucket b,string id) { return ((int)b).ToString()+":"+id; }
        internal static T Copy<T>(T value) where T:class,new() { if(value==null)return null; T result=new T(); foreach(var f in typeof(T).GetFields()) f.SetValue(result,f.GetValue(value)); return result; }
        public FlowSnapshot GetFlowSnapshot() { FlowSnapshot p=Copy(Progress);ActorSnapshot spring;p.CanStartNight=p.Phase==GamePhase.Build && (Event==null || Event.Resolved) && Actors.TryGetValue(SpringId.Value,out spring) && spring.CurrentHp>0; return p; }
        public DayEventState GetDayEventState() { return Copy(Event); }
        public bool TryGetCommandReceipt(Guid id,out string fingerprint,out OperationResult result) { fingerprint=null;return Results.TryGetValue(id,out result)&&Fingerprints.TryGetValue(id,out fingerprint); }
        public bool TryGetCommandHistory(Guid id,out CommandHistoryRecord record) { record=null;string fingerprint,request;OperationResult result;if(!TryGetCommandReceipt(id,out fingerprint,out result))return false;DeploymentRequests.TryGetValue(id,out request);record=new CommandHistoryRecord { CommandId=id.ToString("N"),Fingerprint=fingerprint,DeploymentRequest=request,State=result.State,Error=result.Error,Revision=result.Revision,MessageKey=result.MessageKey };return true; }
        public ValidationResult RecordCommandHistory(CommandHistoryRecord record) { Guid id;if(record==null||!Guid.TryParse(record.CommandId,out id)||id==Guid.Empty||string.IsNullOrEmpty(record.Fingerprint)||record.Revision<0||record.Revision>Progress.Revision)return new ValidationResult(ErrorCode.InvalidArgument,"history.invalid");string fingerprint;OperationResult result;if(TryGetCommandReceipt(id,out fingerprint,out result))return new ValidationResult(fingerprint==record.Fingerprint?ErrorCode.None:ErrorCode.DuplicateCommand,"history.duplicate");RecordCommandReceipt(id,record.Fingerprint,new OperationResult(record.State,record.Error,id,record.Revision,record.MessageKey));if(record.DeploymentRequest!=null)DeploymentRequests[id]=record.DeploymentRequest;return new ValidationResult(ErrorCode.None,null); }
        public void RecordCommandReceipt(Guid id,string fingerprint,OperationResult result) { if(id==Guid.Empty||string.IsNullOrEmpty(fingerprint)||result.CommandId!=id)throw new ArgumentException("Invalid command receipt");string old;OperationResult receipt;if(TryGetCommandReceipt(id,out old,out receipt)){if(old!=fingerprint)throw new ArgumentException("Command ID already has a different request");return;}Fingerprints.Add(id,fingerprint);Results.Add(id,result); }
        public CommandHistoryRecord[] ExportCommandHistory() { List<CommandHistoryRecord> values=new List<CommandHistoryRecord>();foreach(var pair in Results){string fingerprint,request;Fingerprints.TryGetValue(pair.Key,out fingerprint);DeploymentRequests.TryGetValue(pair.Key,out request);OperationResult r=pair.Value;values.Add(new CommandHistoryRecord { CommandId=pair.Key.ToString("N"),Fingerprint=fingerprint,DeploymentRequest=request,State=r.State,Error=r.Error,Revision=r.Revision,MessageKey=r.MessageKey });}values.Sort(delegate(CommandHistoryRecord a,CommandHistoryRecord b){return string.CompareOrdinal(a.CommandId,b.CommandId);});return values.ToArray(); }
        public ValidationResult RestoreCommandHistory(IReadOnlyList<CommandHistoryRecord> records) { Dictionary<Guid,string> fingerprints=new Dictionary<Guid,string>();Dictionary<Guid,string> requests=new Dictionary<Guid,string>();Dictionary<Guid,OperationResult> results=new Dictionary<Guid,OperationResult>();if(records==null)return new ValidationResult(ErrorCode.SaveCorrupt,"history.null");foreach(CommandHistoryRecord r in records){Guid id;if(r==null||!Guid.TryParse(r.CommandId,out id)||id==Guid.Empty||string.IsNullOrEmpty(r.Fingerprint)||r.Revision<0||r.Revision>Progress.Revision||fingerprints.ContainsKey(id)||!Enum.IsDefined(typeof(OperationState),r.State)||!Enum.IsDefined(typeof(ErrorCode),r.Error))return new ValidationResult(ErrorCode.SaveCorrupt,"history.invalid");fingerprints.Add(id,r.Fingerprint);results.Add(id,new OperationResult(r.State,r.Error,id,r.Revision,r.MessageKey));if(r.DeploymentRequest!=null)requests.Add(id,r.DeploymentRequest);}Fingerprints=fingerprints;Results=results;DeploymentRequests=requests;return new ValidationResult(ErrorCode.None,null); }
        public ValidationResult Initialize(NewRunRequest request)
        {
            SessionStateStore temp=new SessionStateStore(Catalog);ValidationResult result;
            try { result=temp.InitializeCore(request);if(result.Error==ErrorCode.None)result=new StateTransactionService(temp,null).Validate(new StateMutationBatch {Context=new CommandContext(Guid.NewGuid(),temp.Progress.RunId,-1)}); }catch(Exception){return new ValidationResult(ErrorCode.InvalidDefinition,"run.initial.invalid");}
            if(result.Error!=ErrorCode.None)return result;Adopt(temp);return result;
        }
        void Adopt(SessionStateStore temp) { Level=temp.ActiveLevel;SpringId=temp.SpringId;RunSeed=temp.RunSeed;Progress=temp.Progress;Cells=temp.Cells;Actors=temp.Actors;Quantities=temp.Quantities;RandomStates=temp.RandomStates;NextEntityId=temp.NextEntityId;NextSpawnSequence=temp.NextSpawnSequence;Event=temp.Event;Results.Clear();Fingerprints.Clear();DeploymentRequests.Clear(); }
        ValidationResult InitializeCore(NewRunRequest request)
        {
            LevelDefinition level; if(request==null || !Catalog.TryGetLevel(request.LevelId,out level) || level.Rows<=0 || level.Columns<=0 || level.CellSize<=0) return new ValidationResult(ErrorCode.InvalidDefinition,"level.invalid");
            Reset(); Level=Copy(level); ActiveLevel.ReservedCells=level.ReservedCells==null?new CellCoord[0]:new List<CellCoord>(level.ReservedCells).ToArray();List<SpawnPointDefinition> spawns=new List<SpawnPointDefinition>();if(level.SpawnPoints!=null)foreach(SpawnPointDefinition s in level.SpawnPoints)spawns.Add(Copy(s));ActiveLevel.SpawnPoints=spawns.ToArray();List<PathDefinition> paths=new List<PathDefinition>();if(level.Paths!=null)foreach(PathDefinition p in level.Paths){PathDefinition copy=Copy(p);copy.Cells=p.Cells==null?new CellCoord[0]:new List<CellCoord>(p.Cells).ToArray();paths.Add(copy);}ActiveLevel.Paths=paths.ToArray();ActiveLevel.InitialOccupants=new InitialOccupant[0];ActiveLevel.InitialResources=new ResourceAmount[0]; RunSeed=request.Seed; Progress=new FlowSnapshot { RunId=Guid.NewGuid().ToString("N"), Mode=request.Mode, Phase=GamePhase.Build, DayIndex=1 };
            for(int y=0;y<level.Rows;y++)for(int x=0;x<level.Columns;x++){ CellCoord c=new CellCoord(x,y); Cells.Add(c,new CellSnapshot { Cell=c,TerrainId="terrain.default",Reserved=c.Equals(level.SpringCell) }); }
            if(level.ReservedCells!=null)foreach(CellCoord c in level.ReservedCells)if(Cells.ContainsKey(c))Cells[c].Reserved=true;
            if(level.SpawnPoints!=null)foreach(SpawnPointDefinition s in level.SpawnPoints)if(Cells.ContainsKey(s.Cell))Cells[s.Cell].Reserved=true;
            if(level.Paths!=null)foreach(PathDefinition p in level.Paths)if(p.Movement==MovementKind.Ground && p.Cells!=null)foreach(CellCoord c in p.Cells)if(Cells.ContainsKey(c))Cells[c].OnGroundPath=true;
            for(int i=0;i<4;i++){ uint s=unchecked(request.Seed+0x9e3779b9u*(uint)(i+1)); RandomStates[(RandomStream)i]=s==0?0x6d2b79f5u:s; }
            GameSettings settings=Catalog.GetSettings(); SpringId=new EntityId(NextEntityId++); Actors.Add(SpringId.Value,new ActorSnapshot { Id=SpringId,Kind=ActorKind.Spring,DefinitionId="spring",Position=Center(level.SpringCell),PreviousPosition=Center(level.SpringCell),CurrentHp=settings.SpringMaxHp,MaxHp=settings.SpringMaxHp,CollisionRadius=settings.SpringCollisionRadiusInCells*level.CellSize,Targetable=true,SpawnSequence=NextSpawnSequence++ });
            if(level.InitialResources!=null)foreach(ResourceAmount r in level.InitialResources){if(r.Amount<0 || !ValidResource(r.Bucket,r.DefinitionId))throw new ArgumentException();Quantities[Key(r.Bucket,r.DefinitionId)]=checked(GetQuantity(r.Bucket,r.DefinitionId)+r.Amount);}
            if(level.InitialOccupants!=null)foreach(InitialOccupant o in level.InitialOccupants){ EntityId id=new EntityId(NextEntityId++); CellSnapshot c=Cells[o.Cell];if(c.Reserved || c.OccupantKind!=OccupantKind.None)throw new ArgumentException(); c.OccupantId=id;c.OccupantKind=o.Kind;c.DefinitionId=o.DefinitionId; TowerDefinition t; ElementDefinition e; if(o.Kind==OccupantKind.Tower && Catalog.TryGetTower(o.DefinitionId,out t)){c.BlocksGround=true;Actors[id.Value]=Tower(id,t,o.Cell);}else if(o.Kind==OccupantKind.ElementBlock && Catalog.TryGetElement(o.DefinitionId,out e))c.BlocksGround=e.BlocksGround;else throw new ArgumentException();if(c.OnGroundPath && c.BlocksGround)throw new ArgumentException(); }
            return new ValidationResult(ErrorCode.None,null);
        }
        internal WorldPoint Center(CellCoord c) { return new WorldPoint(ActiveLevel.Origin.X+(c.X+0.5f)*ActiveLevel.CellSize,ActiveLevel.Origin.Y+(c.Y+0.5f)*ActiveLevel.CellSize); }
        internal ActorSnapshot Tower(EntityId id,TowerDefinition t,CellCoord c) { return new ActorSnapshot { Id=id,Kind=ActorKind.Tower,DefinitionId=t.Id,Position=Center(c),PreviousPosition=Center(c),CollisionRadius=t.CollisionRadiusInCells*ActiveLevel.CellSize,CurrentHp=t.HpPerStack*t.InitialAttackStacks,MaxHp=t.HpPerStack*t.InitialAttackStacks,TowerAttackStacks=t.InitialAttackStacks,Targetable=true,SpawnSequence=NextSpawnSequence++ }; }
        internal long GetQuantity(ResourceBucket b,string id) { long n; return Quantities.TryGetValue(Key(b,id),out n)?n:0; }
        internal bool ValidResource(ResourceBucket bucket,string id) { ElementDefinition e;ItemDefinition i;ResourceDefinition r;return !string.IsNullOrEmpty(id) && (bucket==ResourceBucket.Hand?Catalog.TryGetElement(id,out e):bucket==ResourceBucket.Inventory && (Catalog.TryGetItem(id,out i)||Catalog.TryGetResource(id,out r))); }
        public ValidationResult ValidateCheckpoint(CheckpointData data) { return new SessionStateStore(Catalog).Restore(data); }
        public void AdvancePreviousPositions() { foreach(ActorSnapshot a in Actors.Values)a.PreviousPosition=a.Position; }
        public CheckpointData CaptureCheckpoint(IGameCatalog catalog)
        {
            List<SavedOccupant> occ=new List<SavedOccupant>(); foreach(CellSnapshot c in Cells.Values)if(c.OccupantKind!=OccupantKind.None){ActorSnapshot a;Actors.TryGetValue(c.OccupantId.Value,out a);occ.Add(new SavedOccupant { Id=c.OccupantId,DefinitionId=c.DefinitionId,Kind=c.OccupantKind,Cell=c.Cell,CurrentHp=a==null?0:a.CurrentHp,MaxHp=a==null?0:a.MaxHp,AttackStacks=a==null?0:a.TowerAttackStacks });} occ.Sort(delegate(SavedOccupant a,SavedOccupant b){return a.Id.Value.CompareTo(b.Id.Value);});
            List<ResourceAmount> resources=new List<ResourceAmount>();foreach(var q in Quantities){int sep=q.Key.IndexOf(':');resources.Add(new ResourceAmount((ResourceBucket)int.Parse(q.Key.Substring(0,sep)),q.Key.Substring(sep+1),q.Value));}resources.Sort(delegate(ResourceAmount a,ResourceAmount b){int c=a.Bucket.CompareTo(b.Bucket);return c!=0?c:string.CompareOrdinal(a.DefinitionId,b.DefinitionId);});
            List<RandomState> random=new List<RandomState>();for(int i=0;i<4;i++)random.Add(new RandomState((RandomStream)i,RandomStates[(RandomStream)i]));ActorSnapshot spring=Actors[SpringId.Value];
            return new CheckpointData { SaveVersion=1,ContractVersion=ContractVersion.Value,ConfigVersion=catalog.GetSettings().ConfigVersion,RunId=Progress.RunId,LevelId=ActiveLevel.Id,Mode=Progress.Mode,DayIndex=Progress.DayIndex,LastSettledNight=Progress.LastSettledNight,Revision=Progress.Revision,RunSeed=RunSeed,RandomStates=random.ToArray(),NextEntityId=NextEntityId,NextSpawnSequence=NextSpawnSequence,SpringId=SpringId,SpringHp=spring.CurrentHp,SpringMaxHp=spring.MaxHp,Occupants=occ.ToArray(),Resources=resources.ToArray(),DayEvent=Copy(Event),TutorialShown=Progress.TutorialShown,Milestone50Claimed=Progress.Milestone50Claimed,CommittedCommandIds=new List<Guid>(Results.Keys).ToArray() };
        }
        public ValidationResult Restore(CheckpointData data)
        {
            if(data==null)return new ValidationResult(ErrorCode.SaveCorrupt,"save.null"); SessionStateStore temp=new SessionStateStore(Catalog);ValidationResult v=temp.Initialize(new NewRunRequest { LevelId=data.LevelId,Mode=data.Mode,Seed=data.RunSeed });if(v.Error!=ErrorCode.None)return v;
            try { temp.Actors.Clear();foreach(CellSnapshot c in temp.Cells.Values){c.OccupantKind=OccupantKind.None;c.OccupantId=new EntityId(0);c.DefinitionId=null;c.BlocksGround=false;}temp.SpringId=data.SpringId;temp.Actors[data.SpringId.Value]=new ActorSnapshot { Id=data.SpringId,Kind=ActorKind.Spring,DefinitionId="spring",Position=temp.Center(temp.ActiveLevel.SpringCell),PreviousPosition=temp.Center(temp.ActiveLevel.SpringCell),CurrentHp=data.SpringHp,MaxHp=data.SpringMaxHp,Targetable=data.SpringHp>0,CollisionRadius=Catalog.GetSettings().SpringCollisionRadiusInCells*temp.ActiveLevel.CellSize };
                foreach(SavedOccupant o in data.Occupants){CellSnapshot c=temp.Cells[o.Cell];if(c.OccupantKind!=OccupantKind.None || c.Reserved || o.Id.Value<=0)throw new ArgumentException();c.OccupantKind=o.Kind;c.OccupantId=o.Id;c.DefinitionId=o.DefinitionId;TowerDefinition t;ElementDefinition e;if(o.Kind==OccupantKind.Tower && Catalog.TryGetTower(o.DefinitionId,out t)){c.BlocksGround=true;ActorSnapshot a=temp.Tower(o.Id,t,o.Cell);a.CurrentHp=o.CurrentHp;a.MaxHp=o.MaxHp;a.TowerAttackStacks=o.AttackStacks;temp.Actors.Add(o.Id.Value,a);}else if(o.Kind==OccupantKind.ElementBlock && Catalog.TryGetElement(o.DefinitionId,out e))c.BlocksGround=e.BlocksGround;else throw new ArgumentException();if(c.OnGroundPath && c.BlocksGround)throw new ArgumentException();}
                temp.Quantities.Clear();foreach(ResourceAmount r in data.Resources){if(r.Amount<0 || !temp.ValidResource(r.Bucket,r.DefinitionId))throw new ArgumentException();temp.Quantities.Add(Key(r.Bucket,r.DefinitionId),r.Amount);}temp.RandomStates.Clear();foreach(RandomState r in data.RandomStates){if(r.State==0 || !Enum.IsDefined(typeof(RandomStream),r.Stream))throw new ArgumentException();temp.RandomStates.Add(r.Stream,r.State);}if(temp.RandomStates.Count!=4)throw new ArgumentException();temp.Progress=new FlowSnapshot { RunId=data.RunId,Mode=data.Mode,Phase=data.DayEvent!=null && !data.DayEvent.Resolved?GamePhase.DayEvent:GamePhase.Build,DayIndex=data.DayIndex,LastSettledNight=data.LastSettledNight,Revision=data.Revision,TutorialShown=data.TutorialShown,Milestone50Claimed=data.Milestone50Claimed };temp.NextEntityId=data.NextEntityId;temp.NextSpawnSequence=data.NextSpawnSequence;temp.Event=Copy(data.DayEvent);foreach(long id in temp.Actors.Keys)if(id>=temp.NextEntityId)throw new ArgumentException();foreach(CellSnapshot c in temp.Cells.Values)if(c.OccupantId.Value>=temp.NextEntityId)throw new ArgumentException();if(data.SpringId.Value<=0 || data.NextSpawnSequence<1 || data.DayIndex<1 || data.LastSettledNight<0 || data.LastSettledNight>=data.DayIndex || data.Revision<0 || string.IsNullOrEmpty(data.RunId))throw new ArgumentException();ValidationResult validity=new StateTransactionService(temp,null).Validate(new StateMutationBatch {Context=new CommandContext(Guid.NewGuid(),data.RunId,-1)});if(validity.Error!=ErrorCode.None)throw new ArgumentException();
            }catch(Exception){return new ValidationResult(ErrorCode.SaveCorrupt,"save.invalid");}
            Adopt(temp);if(data.CommittedCommandIds!=null)foreach(Guid id in data.CommittedCommandIds){Results[id]=new OperationResult(OperationState.Committed,ErrorCode.None,id,data.Revision,null);Fingerprints[id]="restored";}return new ValidationResult(ErrorCode.None,null);
        }
    }
}



