using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using Spotlight.Contracts;
namespace Spotlight.Core
{
    public sealed class StateTransactionService : IStateTransactionService
    {
        readonly SessionStateStore store; readonly IEventBus events;
        public StateTransactionService(SessionStateStore store,IEventBus events) { this.store=store;this.events=events; }
        public long Revision { get { return store.Progress.Revision; } }
        sealed class Prepared { public Dictionary<CellCoord,CellSnapshot> Cells; public Dictionary<long,ActorSnapshot> Actors;public Dictionary<string,long> Resources;public Dictionary<RandomStream,uint> Random; }
        static void Append(StringBuilder b,object o) { if(o==null){b.Append("null;");return;}Type t=o.GetType();if(t.IsPrimitive || t.IsEnum || o is string || o is Guid){string s=Convert.ToString(o,CultureInfo.InvariantCulture);b.Append(s.Length).Append(':').Append(s).Append(';');return;}IEnumerable list=o as IEnumerable;if(list!=null){b.Append('[');foreach(object v in list)Append(b,v);b.Append(']');return;}b.Append(t.Name).Append('{');foreach(var f in t.GetFields()){b.Append(f.Name).Append('=');Append(b,f.GetValue(o));}b.Append('}'); }
        static string Fingerprint(StateMutationBatch batch) { StringBuilder b=new StringBuilder();Append(b,batch);return b.ToString(); }
        ErrorCode Prepare(StateMutationBatch batch,out Prepared p)
        {
            p=null;if(batch==null || batch.Context.CommandId==Guid.Empty)return ErrorCode.InvalidArgument;
            Spotlight.Core.Events.GameEventBus eventBus=events as Spotlight.Core.Events.GameEventBus;if(eventBus!=null&&eventBus.IsDispatching)return ErrorCode.WrongPhase;
            if(batch.Context.RunId!=store.Progress.RunId)return ErrorCode.WrongRun;
            if(batch.Context.ExpectedRevision!=-1 && batch.Context.ExpectedRevision!=Revision)return ErrorCode.VersionConflict;
            Prepared state=new Prepared { Cells=new Dictionary<CellCoord,CellSnapshot>(),Actors=new Dictionary<long,ActorSnapshot>(),Resources=new Dictionary<string,long>(store.Quantities),Random=new Dictionary<RandomStream,uint>(store.RandomStates) };
            foreach(var c in store.Cells)state.Cells.Add(c.Key,SessionStateStore.Copy(c.Value));foreach(var a in store.Actors)state.Actors.Add(a.Key,SessionStateStore.Copy(a.Value));
            try {
                if(batch.ResourceDeltas!=null){Dictionary<string,long> sums=new Dictionary<string,long>();foreach(ResourceAmount r in batch.ResourceDeltas){ElementDefinition e;ItemDefinition i;ResourceDefinition d;if(string.IsNullOrEmpty(r.DefinitionId) || (r.Bucket==ResourceBucket.Hand?!store.Catalog.TryGetElement(r.DefinitionId,out e):r.Bucket!=ResourceBucket.Inventory || (!store.Catalog.TryGetItem(r.DefinitionId,out i) && !store.Catalog.TryGetResource(r.DefinitionId,out d))))return ErrorCode.InvalidDefinition;string k=SessionStateStore.Key(r.Bucket,r.DefinitionId);long old;sums.TryGetValue(k,out old);sums[k]=checked(old+r.Amount);}foreach(var r in sums){long n;state.Resources.TryGetValue(r.Key,out n);n=checked(n+r.Value);if(n<0)return ErrorCode.InsufficientQuantity;state.Resources[r.Key]=n;}}
                if(batch.Board!=null){HashSet<long> consumed=new HashSet<long>();foreach(BoardMutation m in batch.Board){if(m==null || m.EntityId.Value<=0 || !Enum.IsDefined(typeof(BoardMutationKind),m.Kind))return ErrorCode.InvalidArgument;if(!consumed.Add(m.EntityId.Value))return ErrorCode.InvalidArgument;if(m.Kind!=BoardMutationKind.Place){CellSnapshot c;if(!state.Cells.TryGetValue(m.From,out c))return ErrorCode.OutOfBounds;if(c.OccupantKind==OccupantKind.None)return ErrorCode.EmptyCell;if(!c.OccupantId.Equals(m.EntityId) || c.OccupantKind!=m.OccupantKind || c.DefinitionId!=m.DefinitionId)return ErrorCode.InvalidTarget;c.OccupantKind=OccupantKind.None;c.OccupantId=new EntityId(0);c.DefinitionId=null;c.BlocksGround=false;}}
                    foreach(BoardMutation m in batch.Board)if(m.Kind!=BoardMutationKind.Remove){CellSnapshot c;if(!state.Cells.TryGetValue(m.To,out c))return ErrorCode.OutOfBounds;if(c.Reserved)return ErrorCode.ReservedCell;if(c.OccupantKind!=OccupantKind.None)return ErrorCode.Occupied;TowerDefinition t;ElementDefinition e;bool blocks;if(m.OccupantKind==OccupantKind.Tower && store.Catalog.TryGetTower(m.DefinitionId,out t))blocks=true;else if(m.OccupantKind==OccupantKind.ElementBlock && store.Catalog.TryGetElement(m.DefinitionId,out e))blocks=e.BlocksGround;else return ErrorCode.InvalidDefinition;if(c.OnGroundPath && blocks)return ErrorCode.InvalidPathPlacement;c.OccupantId=m.EntityId;c.OccupantKind=m.OccupantKind;c.DefinitionId=m.DefinitionId;c.BlocksGround=blocks;}}
                if(batch.Actors!=null)foreach(ActorMutation m in batch.Actors){if(m==null || m.ActorId.Value<=0)return ErrorCode.InvalidArgument;ActorSnapshot a;if(m.Kind==ActorMutationKind.Register){if(m.Registration==null || !m.Registration.Id.Equals(m.ActorId) || state.Actors.ContainsKey(m.ActorId.Value))return ErrorCode.InvalidTarget;a=SessionStateStore.Copy(m.Registration);a.PreviousPosition=a.Position;state.Actors.Add(m.ActorId.Value,a);}else{if(!state.Actors.TryGetValue(m.ActorId.Value,out a))return ErrorCode.InvalidTarget;switch(m.Kind){case ActorMutationKind.Remove:state.Actors.Remove(m.ActorId.Value);break;case ActorMutationKind.SetHealth:a.CurrentHp=m.CurrentHp;a.MaxHp=m.MaxHp;if(a.CurrentHp<=0)a.Targetable=false;break;case ActorMutationKind.SetTowerStacks:if(a.Kind!=ActorKind.Tower)return ErrorCode.InvalidTarget;a.TowerAttackStacks=m.TowerAttackStacks;break;case ActorMutationKind.MarkDeathResolved:if(a.CurrentHp>0 || a.DeathResolved)return ErrorCode.InvalidTarget;a.DeathResolved=true;break;default:return ErrorCode.InvalidArgument;}}}
                HashSet<long> ids=new HashSet<long>();HashSet<long> towers=new HashSet<long>();foreach(CellSnapshot c in state.Cells.Values)if(c.OccupantKind!=OccupantKind.None){if(!ids.Add(c.OccupantId.Value))return ErrorCode.InvalidTarget;if(c.OccupantKind==OccupantKind.Tower){ActorSnapshot a;if(!state.Actors.TryGetValue(c.OccupantId.Value,out a) || a.Kind!=ActorKind.Tower || a.DefinitionId!=c.DefinitionId)return ErrorCode.InvalidTarget;a.Position=store.Center(c.Cell);if(!store.Actors.ContainsKey(a.Id.Value))a.PreviousPosition=a.Position;towers.Add(a.Id.Value);}else if(state.Actors.ContainsKey(c.OccupantId.Value))return ErrorCode.InvalidTarget;}
                foreach(ActorSnapshot a in state.Actors.Values){if(a.Kind==ActorKind.Tower && !towers.Contains(a.Id.Value))return ErrorCode.InvalidTarget;if(float.IsNaN(a.CurrentHp) || float.IsInfinity(a.CurrentHp) || float.IsNaN(a.MaxHp) || float.IsInfinity(a.MaxHp) || a.MaxHp<=0 || a.CurrentHp<0 || a.CurrentHp>a.MaxHp || a.CollisionRadius<0 || float.IsNaN(a.CollisionRadius) || float.IsNaN(a.Position.X) || float.IsNaN(a.Position.Y) || float.IsInfinity(a.Position.X) || float.IsInfinity(a.Position.Y))return ErrorCode.InvalidArgument;if(a.Kind==ActorKind.Tower){TowerDefinition t;if(!store.Catalog.TryGetTower(a.DefinitionId,out t) || a.TowerAttackStacks<1 || a.TowerAttackStacks>t.MaxAttackStacks)return ErrorCode.InvalidArgument;}else if(a.Kind==ActorKind.Enemy){EnemyDefinition e;if(!store.Catalog.TryGetEnemy(a.DefinitionId,out e))return ErrorCode.InvalidDefinition;}else if(a.Kind!=ActorKind.Spring)return ErrorCode.InvalidDefinition;}
                if(batch.Random!=null){HashSet<RandomStream> streams=new HashSet<RandomStream>();foreach(RandomStateWrite r in batch.Random){uint current;if(r==null || !streams.Add(r.Before.Stream) || r.Before.Stream!=r.After.Stream || r.After.State==0 || !state.Random.TryGetValue(r.Before.Stream,out current) || current!=r.Before.State)return ErrorCode.VersionConflict;state.Random[r.After.Stream]=r.After.State;}}
                if(batch.Progress!=null){ProgressPatch r=batch.Progress;if(r.DayIndex<1 || r.LastSettledNight<store.Progress.LastSettledNight || r.LastSettledNight>r.DayIndex || !Enum.IsDefined(typeof(GamePhase),r.Phase))return ErrorCode.InvalidArgument;if((batch.Reason=="DawnSettlement" || batch.Reason=="dawn.settle" || r.DayIndex>store.Progress.DayIndex) && r.LastSettledNight<=store.Progress.LastSettledNight)return ErrorCode.DuplicateCommand;}
                if(batch.DayEvent!=null && (batch.DayEvent.DayIndex<1 || string.IsNullOrEmpty(batch.DayEvent.InstanceId) || (!batch.DayEvent.Resolved && string.IsNullOrEmpty(batch.DayEvent.DefinitionId))))return ErrorCode.InvalidArgument;
            }catch(OverflowException){return ErrorCode.InvalidArgument;}
            p=state;return ErrorCode.None;
        }
        public ValidationResult Validate(StateMutationBatch batch) { Prepared p;ErrorCode e=Prepare(batch,out p);return new ValidationResult(e,e==ErrorCode.None?null:"transaction."+e.ToString()); }
        public OperationResult TryCommit(StateMutationBatch batch)
        {
            if(batch==null)return new OperationResult(OperationState.Rejected,ErrorCode.InvalidArgument,Guid.Empty,Revision,"transaction.null");string fingerprint=Fingerprint(batch);OperationResult prior;if(store.Results.TryGetValue(batch.Context.CommandId,out prior)){string old=store.Fingerprints[batch.Context.CommandId];return old==fingerprint?prior:new OperationResult(OperationState.Rejected,ErrorCode.DuplicateCommand,batch.Context.CommandId,Revision,"transaction.duplicate");}
            Prepared p;ErrorCode error=Prepare(batch,out p);if(error!=ErrorCode.None)return new OperationResult(OperationState.Rejected,error,batch.Context.CommandId,Revision,"transaction."+error.ToString());
            Dictionary<long,ActorSnapshot> priorActors=store.Actors;GamePhase oldPhase=store.Progress.Phase;store.Cells=p.Cells;store.Actors=p.Actors;store.Quantities=p.Resources;store.RandomStates=p.Random;if(batch.Progress!=null){ProgressPatch r=batch.Progress;store.Progress.Phase=r.Phase;store.Progress.DayIndex=r.DayIndex;store.Progress.LastSettledNight=r.LastSettledNight;store.Progress.Milestone50Claimed=r.Milestone50Claimed;store.Progress.TutorialShown=r.TutorialShown;}if(batch.DayEvent!=null)store.Event=SessionStateStore.Copy(batch.DayEvent);store.Progress.Revision++;
            OperationResult result=new OperationResult(OperationState.Committed,ErrorCode.None,batch.Context.CommandId,Revision,null);store.Results.Add(batch.Context.CommandId,result);store.Fingerprints.Add(batch.Context.CommandId,fingerprint);
            if(events!=null){if(oldPhase!=store.Progress.Phase)Publish(new PhaseChangedEvent { OldPhase=oldPhase,NewPhase=store.Progress.Phase,DayIndex=store.Progress.DayIndex });if(batch.Board!=null && batch.Board.Count>0){List<CellCoord> cells=new List<CellCoord>();foreach(BoardMutation m in batch.Board){if(m.Kind!=BoardMutationKind.Place)cells.Add(m.From);if(m.Kind!=BoardMutationKind.Remove)cells.Add(m.To);}Publish(new BoardChangedEvent { Revision=Revision,Cells=cells.ToArray() });}if(batch.ResourceDeltas!=null && batch.ResourceDeltas.Count>0)Publish(new ResourcesChangedEvent { Revision=Revision,Deltas=new List<ResourceAmount>(batch.ResourceDeltas).ToArray() });if(batch.Actors!=null)foreach(ActorMutation m in batch.Actors){if(m.Kind==ActorMutationKind.Register)Publish(new ActorSpawnedEvent { Actor=m.ActorId,DefinitionId=m.Registration.DefinitionId,Kind=m.Registration.Kind });else if(m.Kind==ActorMutationKind.Remove){ActorSnapshot removed;if(priorActors.TryGetValue(m.ActorId.Value,out removed) && removed.Kind!=ActorKind.Enemy)Publish(new ActorRemovedEvent { Actor=m.ActorId,Reason=DeathReason.ScriptedExit });}else if(m.Kind==ActorMutationKind.SetHealth)Publish(new HealthChangedEvent { Actor=m.ActorId,CurrentHp=m.CurrentHp,MaxHp=m.MaxHp });}}return result;
        }
        void Publish<T>(T value) where T:class { try{events.Publish(value);}catch(Exception){ /* Business commit survives presentation subscribers. */ } }
    }
}

