using System;
using System.Collections.Generic;
using Spotlight.Contracts;
namespace Spotlight.Gameplay {
public sealed class GameplayServices : ISessionModule,ITickSystem,IItemService,IDayEventService {
 readonly IGameCatalog catalog; readonly IWorldQuery world; readonly IStateTransactionService tx; readonly ICommandContextFactory commands; readonly IRandomService random; readonly IEffectService effects; readonly IGameClock clock; readonly IEventBus events; readonly Func<FlowSnapshot> flow; readonly IResourceQuery resources; readonly Func<DayEventState> readEvent;
 sealed class Pending {public CommandContext Context;public ItemUseRequest Request;public string Group;}
 readonly List<Pending> queue=new List<Pending>(); readonly Dictionary<string,ItemGroupSnapshot> active=new Dictionary<string,ItemGroupSnapshot>(); readonly Dictionary<Guid,OperationResult> results=new Dictionary<Guid,OperationResult>();readonly Dictionary<Guid,string> bodies=new Dictionary<Guid,string>(); DayEventState dayEvent; bool started;
 public GameplayServices(IGameCatalog catalog,IWorldQuery world,IStateTransactionService tx,ICommandContextFactory commands,IRandomService random,IEffectService effects,IGameClock clock,IEventBus events,Func<FlowSnapshot> flow,IResourceQuery resources,Func<DayEventState> readDayEvent){this.catalog=catalog;this.world=world;this.tx=tx;this.commands=commands;this.random=random;this.effects=effects;this.clock=clock;this.events=events;this.flow=flow;this.resources=resources;readEvent=readDayEvent;}
 public IItemService Items {get{return this;}}public IDayEventService DayEvents {get{return this;}}public IReadOnlyList<ITickSystem> TickSystems{get{return new ITickSystem[]{this};}}public ModuleId Module{get{return ModuleId.Gameplay;}}public IReadOnlyList<TickStage> Stages{get{return new[]{TickStage.PlayerCommands};}}
 public void BeginSession(SessionStartContext context){EndSession();started=true;dayEvent=Copy(readEvent());}public void EndSession(){ResetTransient();results.Clear();bodies.Clear();dayEvent=null;started=false;}
 static DayEventState Copy(DayEventState s){return s==null?null:new DayEventState{DayIndex=s.DayIndex,InstanceId=s.InstanceId,DefinitionId=s.DefinitionId,Resolved=s.Resolved,ChosenOptionId=s.ChosenOptionId};}
 OperationResult Reject(CommandContext c,ErrorCode e){return new OperationResult(OperationState.Rejected,e,c.CommandId,tx.Revision,null);} ValidationResult Invalid(ErrorCode e){return new ValidationResult(e,null);}
 EffectBatchRequest ItemBatch(CommandContext c,ItemUseRequest request,ItemDefinition d){return new EffectBatchRequest{Context=c,Source=world.SpringId,SelectedTarget=request.Target,Origin=DamageOrigin.Item,Effects=d.Effects,CommitExtras=new StateMutationBatch{Context=c,Reason="item.use",ResourceDeltas=new[]{new ResourceAmount(ResourceBucket.Inventory,d.Id,-1)}}};}
 ValidationResult Check(ItemUseRequest request,string ownGroup){if(!started||request==null)return Invalid(ErrorCode.InvalidArgument);var f=flow();ItemDefinition d;if(!catalog.TryGetItem(request.ItemId,out d))return Invalid(ErrorCode.InvalidDefinition);bool phase=false;if(d.AllowedPhases!=null)foreach(var p in d.AllowedPhases)if(p==f.Phase)phase=true;if(!phase)return Invalid(ErrorCode.WrongPhase);if(resources.GetQuantity(ResourceBucket.Inventory,d.Id)<1)return Invalid(ErrorCode.InsufficientQuantity);if(!string.IsNullOrEmpty(d.StackingGroup)){if(active.ContainsKey(d.StackingGroup))return Invalid(ErrorCode.EffectAlreadyActive);foreach(var p in queue)if(p.Group==d.StackingGroup&&p.Group!=ownGroup)return Invalid(ErrorCode.EffectAlreadyActive);}return effects.Validate(ItemBatch(commands.Create(tx.Revision),request,d));}
 public ValidationResult CheckUse(ItemUseRequest request){return Check(request,null);}
 public OperationResult TryUse(CommandContext context,ItemUseRequest request){if(context.CommandId==Guid.Empty)return Reject(context,ErrorCode.InvalidArgument);string body="item:"+(request==null?"null":request.ItemId+":"+request.Target.Value);string priorBody;if(bodies.TryGetValue(context.CommandId,out priorBody)&&priorBody!=body)return Reject(context,ErrorCode.DuplicateCommand);OperationResult old;if(results.TryGetValue(context.CommandId,out old))return old;foreach(var p in queue)if(p.Context.CommandId==context.CommandId)return new OperationResult(OperationState.Queued,ErrorCode.None,context.CommandId,tx.Revision,null);var check=CheckUse(request);if(check.Error!=ErrorCode.None)return Reject(context,check.Error);var f=flow();if(context.RunId!=f.RunId)return Reject(context,ErrorCode.WrongRun);if(context.ExpectedRevision!=tx.Revision)return Reject(context,ErrorCode.VersionConflict);ItemDefinition d;catalog.TryGetItem(request.ItemId,out d);bodies[context.CommandId]=body;if(f.Phase==GamePhase.Night){queue.Add(new Pending{Context=context,Request=new ItemUseRequest{ItemId=request.ItemId,Target=request.Target},Group=d.StackingGroup});return new OperationResult(OperationState.Queued,ErrorCode.None,context.CommandId,tx.Revision,null);}return Execute(context,request,d);}
 OperationResult Execute(CommandContext c,ItemUseRequest r,ItemDefinition d){var result=effects.TryExecute(ItemBatch(c,r,d));results[c.CommandId]=result;if(result.State==OperationState.Committed&&d.ActiveDurationSeconds>0&&!string.IsNullOrEmpty(d.StackingGroup))active[d.StackingGroup]=new ItemGroupSnapshot{StackingGroup=d.StackingGroup,ItemId=d.Id,RemainingSeconds=d.ActiveDurationSeconds};return result;}
 public IReadOnlyList<ItemGroupSnapshot> GetActiveGroups(){var list=new List<ItemGroupSnapshot>();foreach(var s in active.Values)list.Add(new ItemGroupSnapshot{StackingGroup=s.StackingGroup,ItemId=s.ItemId,RemainingSeconds=s.RemainingSeconds});foreach(var p in queue)if(!string.IsNullOrEmpty(p.Group))list.Add(new ItemGroupSnapshot{StackingGroup=p.Group,ItemId=p.Request.ItemId,PendingCommand=true});return list.ToArray();}
 public void ResetTransient(){foreach(var p in queue)events.Publish(new CommandFinishedEvent{Result=Reject(p.Context,ErrorCode.WrongRun)});queue.Clear();active.Clear();}
 public void Tick(TickContext context){if(!started||context.Stage!=TickStage.PlayerCommands||clock.GetSnapshot().IsPaused)return;foreach(var key in new List<string>(active.Keys)){active[key].RemainingSeconds-=context.DeltaSeconds;if(active[key].RemainingSeconds<=0)active.Remove(key);}foreach(var p in new List<Pending>(queue)){var check=Check(p.Request,p.Group);OperationResult result;if(flow().Phase!=GamePhase.Night)result=Reject(p.Context,ErrorCode.WrongPhase);else if(check.Error!=ErrorCode.None)result=Reject(p.Context,check.Error);else{ItemDefinition d;catalog.TryGetItem(p.Request.ItemId,out d);var current=new CommandContext(p.Context.CommandId,p.Context.RunId,tx.Revision);result=Execute(current,p.Request,d);}queue.Remove(p);results[p.Context.CommandId]=result;events.Publish(new CommandFinishedEvent{Result=result});}}
 public DayEventSnapshot GetSnapshot(){var state=Copy(readEvent());if(state!=null)dayEvent=state;DayEventDefinition d;return new DayEventSnapshot{State=Copy(dayEvent),Text=dayEvent!=null&&catalog.TryGetEvent(dayEvent.DefinitionId,out d)?d.Text:null,Options=EventOptions()};}
 static IReadOnlyList<EffectSpec> CopyEffects(IReadOnlyList<EffectSpec> input){if(input==null)return null;var result=new List<EffectSpec>();foreach(var e in input)result.Add(new EffectSpec{Id=e.Id,Kind=e.Kind,TargetPolicy=e.TargetPolicy,ReferenceId=e.ReferenceId,ResourceBucket=e.ResourceBucket,ResourceAmount=e.ResourceAmount,PhysicalDamage=e.PhysicalDamage,ElementDamage=e.ElementDamage,Gauge=e.Gauge,Amount=e.Amount,Stacks=e.Stacks,DurationOverride=e.DurationOverride,DamageMultiplier=e.DamageMultiplier,SpeedMultiplier=e.SpeedMultiplier});return result.ToArray();} IReadOnlyList<EventOptionDefinition> EventOptions(){DayEventDefinition d;var list=new List<EventOptionDefinition>();if(dayEvent!=null&&!string.IsNullOrEmpty(dayEvent.DefinitionId)&&catalog.TryGetEvent(dayEvent.DefinitionId,out d)&&d.Options!=null)foreach(var o in d.Options)list.Add(new EventOptionDefinition{Id=o.Id,Text=o.Text,Cost=o.Cost==null?null:new List<ResourceAmount>(o.Cost).ToArray(),Effects=CopyEffects(o.Effects)});return list.ToArray();}
 public OperationResult EnsureEvent(int dayIndex,GameMode mode){var f=flow();var c=commands.Create(tx.Revision);if(!started||f.Phase!=GamePhase.DayEvent||f.DayIndex!=dayIndex||f.Mode!=mode)return Reject(c,ErrorCode.WrongPhase);var saved=readEvent();if(saved!=null)dayEvent=Copy(saved);if(dayEvent!=null&&dayEvent.DayIndex==dayIndex)return new OperationResult(OperationState.Committed,ErrorCode.None,c.CommandId,tx.Revision,null);
  var eligible=new List<DayEventDefinition>();foreach(var d in catalog.GetDayEvents()){bool allowed=false;if(d.Modes!=null)foreach(var m in d.Modes)if(m==mode)allowed=true;if(allowed&&d.Weight>0&&dayIndex>=d.MinDayInclusive&&dayIndex<=d.MaxDayInclusive)eligible.Add(d);}eligible.Sort(delegate(DayEventDefinition a,DayEventDefinition b){return string.CompareOrdinal(a.Id,b.Id);});long total=0;foreach(var d in eligible)total+=d.Weight;var before=random.GetState(RandomStream.DayEvent);var cursor=random.CreateCursor(before);DayEventDefinition chosen=null;if(total>0){long pick=Draw(cursor,total);foreach(var d in eligible){if(pick<d.Weight){chosen=d;break;}pick-=d.Weight;}}
  var state=new DayEventState{DayIndex=dayIndex,InstanceId=Guid.NewGuid().ToString("N"),DefinitionId=chosen==null?null:chosen.Id,Resolved=chosen==null};var result=tx.TryCommit(new StateMutationBatch{Context=c,Reason="dayevent.draw",DayEvent=state,Random=new[]{new RandomStateWrite{Before=before,After=cursor.Capture()}}});if(result.State==OperationState.Committed){dayEvent=Copy(state);events.Publish(new DayEventChangedEvent{Snapshot=GetSnapshot()});}return result;
 }
 static long Draw(IRandomCursor cursor,long bound){if(bound<=int.MaxValue)return cursor.NextInt(0,(int)bound);ulong size=1UL<<62,limit=size-size%(ulong)bound,value;do{value=((ulong)cursor.NextInt(0,1<<30)<<32)|((ulong)cursor.NextInt(0,1<<30)<<2)|(uint)cursor.NextInt(0,4);}while(value>=limit);return (long)(value%(ulong)bound);}
 public OperationResult TryChoose(CommandContext context,string instanceId,string optionId){if(context.CommandId==Guid.Empty)return Reject(context,ErrorCode.InvalidArgument);string body="event:"+instanceId+":"+optionId;string priorBody;if(bodies.TryGetValue(context.CommandId,out priorBody)&&priorBody!=body)return Reject(context,ErrorCode.DuplicateCommand);OperationResult previous;if(results.TryGetValue(context.CommandId,out previous))return previous;var f=flow();GetSnapshot();if(!started||f.Phase!=GamePhase.DayEvent)return Reject(context,ErrorCode.WrongPhase);if(dayEvent==null||dayEvent.Resolved||dayEvent.InstanceId!=instanceId||dayEvent.DayIndex!=f.DayIndex)return Reject(context,ErrorCode.InvalidOption);DayEventDefinition definition;if(!catalog.TryGetEvent(dayEvent.DefinitionId,out definition))return Reject(context,ErrorCode.InvalidDefinition);EventOptionDefinition option=null;foreach(var o in definition.Options)if(o.Id==optionId)option=o;if(option==null)return Reject(context,ErrorCode.InvalidOption);var costs=new List<ResourceAmount>();if(option.Cost!=null)foreach(var cost in option.Cost){if(cost.Amount<0)return Reject(context,ErrorCode.InvalidDefinition);costs.Add(new ResourceAmount(cost.Bucket,cost.DefinitionId,-cost.Amount));}var state=Copy(dayEvent);state.Resolved=true;state.ChosenOptionId=optionId;var result=effects.TryExecute(new EffectBatchRequest{Context=context,Source=world.SpringId,Origin=DamageOrigin.Event,Effects=option.Effects,CommitExtras=new StateMutationBatch{Context=context,Reason="dayevent.choose",ResourceDeltas=costs.ToArray(),DayEvent=state}});if(result.State==OperationState.Committed){bodies[context.CommandId]=body;results[context.CommandId]=result;dayEvent=state;events.Publish(new DayEventChangedEvent{Snapshot=GetSnapshot()});}return result;}
}
}





