using System;
using System.Collections.Generic;
using Spotlight.Contracts;
namespace Spotlight.Core.Flow {
public sealed class GameFlowService : IGameFlowService, ITickSystem {
 readonly CoreServices core; readonly IGameCatalog catalog; readonly IElementRuleService rules; readonly ISaveService saves; readonly IWaveService waves; readonly IDamageService damage; readonly ISpecialSkillService skill; readonly ITowerService towers; readonly IProjectileService projectiles; readonly IItemService items; readonly IDayEventService dayEvents; readonly IGameClock clock; readonly ISimulationDriver driver; readonly IEventBus events; readonly IReadOnlyList<ISessionModule> modules;
 sealed class Receipt { public string Body; public OperationResult Result; } readonly Dictionary<Guid,Receipt> receipts=new Dictionary<Guid,Receipt>(); bool synchronizing;
 public GameFlowService(CoreServices core,IGameCatalog catalog,IElementRuleService rules,ISaveService saves,IWaveService waves,IDamageService damage,ISpecialSkillService skill,ITowerService towers,IProjectileService projectiles,IItemService items,IDayEventService dayEvents,IGameClock clock,ISimulationDriver driver,IEventBus events,IReadOnlyList<ISessionModule> modules) { this.core=core;this.catalog=catalog;this.rules=rules;this.saves=saves;this.waves=waves;this.damage=damage;this.skill=skill;this.towers=towers;this.projectiles=projectiles;this.items=items;this.dayEvents=dayEvents;this.clock=clock;this.driver=driver;this.events=events;this.modules=modules; }
 public ModuleId Module {get{return ModuleId.Core;}} public IReadOnlyList<TickStage> Stages {get{return new[]{TickStage.Outcome};}} public FlowSnapshot GetSnapshot(){return core.Store.GetFlowSnapshot();}
 OperationResult Reject(CommandContext c,ErrorCode e){return new OperationResult(OperationState.Rejected,e,c.CommandId,core.Transactions.Revision,"flow."+e);}
 OperationResult Success(CommandContext c){return new OperationResult(OperationState.Committed,ErrorCode.None,c.CommandId,core.Transactions.Revision,null);}
 bool Check(CommandContext c,string body,out OperationResult r){body=Fingerprint(new object[]{c.RunId,c.ExpectedRevision,body});Receipt prior;if(receipts.TryGetValue(c.CommandId,out prior)){r=prior.Body==body?prior.Result:Reject(c,ErrorCode.DuplicateCommand);return false;}CommandHistoryRecord saved;if(core.Store.TryGetCommandHistory(c.CommandId,out saved)){r=saved.Fingerprint=="flow:"+body?new OperationResult(saved.State,saved.Error,c.CommandId,saved.Revision,saved.MessageKey):Reject(c,ErrorCode.DuplicateCommand);return false;}var f=GetSnapshot();ErrorCode e=c.CommandId==Guid.Empty?ErrorCode.InvalidArgument:c.RunId!=f.RunId?ErrorCode.WrongRun:c.ExpectedRevision!=f.Revision?ErrorCode.VersionConflict:ErrorCode.None;r=Reject(c,e);return e==ErrorCode.None;}
 OperationResult Finish(CommandContext c,string body,OperationResult r){body=Fingerprint(new object[]{c.RunId,c.ExpectedRevision,body});if(r.State==OperationState.Committed){r=Success(c);var recorded=core.Store.RecordCommandHistory(new CommandHistoryRecord{CommandId=c.CommandId.ToString("N"),Fingerprint="flow:"+body,State=r.State,Error=r.Error,Revision=r.Revision,MessageKey=r.MessageKey});if(recorded.Error!=ErrorCode.None)return Reject(c,recorded.Error);receipts[c.CommandId]=new Receipt{Body=body,Result=r};if(GetSnapshot().Phase==GamePhase.Build)saves.SaveCheckpoint(core.Commands.Create(core.Transactions.Revision),SaveReason.DeploymentChanged);}return r;}
 ProgressPatch Patch(GamePhase phase){var f=GetSnapshot();return new ProgressPatch{Phase=phase,DayIndex=f.DayIndex,LastSettledNight=f.LastSettledNight,Milestone50Claimed=f.Milestone50Claimed,TutorialShown=f.TutorialShown};}
 OperationResult Phase(GamePhase phase){return core.Transactions.TryCommit(new StateMutationBatch{Context=core.Commands.Create(core.Transactions.Revision),Reason="flow.phase",Progress=Patch(phase)});}
 bool SpringAlive(){ActorSnapshot a;return core.World.TryGetActor(core.World.SpringId,out a)&&a.CurrentHp>0;}
 void Begin(bool load){var f=GetSnapshot();foreach(var m in modules)m.BeginSession(new SessionStartContext{RunId=f.RunId,Mode=f.Mode,LevelId=core.Store.Level.Id,DayIndex=f.DayIndex,SpringId=core.World.SpringId,IsLoad=load});towers.SynchronizeBoard();}
 void End(DeathReason reason){waves.Stop();foreach(var m in modules){var enemy=m as IEnemyService;if(enemy!=null)enemy.DespawnAll(reason);}for(int i=modules.Count-1;i>=0;i--)modules[i].EndSession();projectiles.Clear();items.ResetTransient();driver.Reset();}
 public OperationResult TryNewRun(CommandContext c,NewRunRequest request){string body="new:"+(request==null?"null":request.LevelId+":"+(int)request.Mode+":"+request.Seed);OperationResult r;if(!Check(c,body,out r))return r;if(GetSnapshot().Phase!=GamePhase.Menu)return Reject(c,ErrorCode.WrongPhase);if(request==null||!Enum.IsDefined(typeof(GameMode),request.Mode))return Reject(c,ErrorCode.InvalidArgument);var errors=catalog.ValidateAll();if(errors!=null&&errors.Count>0)return Reject(c,ErrorCode.InvalidDefinition);var old=GetSnapshot().Phase;var initialized=core.Store.Initialize(request);if(initialized.Error!=ErrorCode.None)return Reject(c,initialized.Error);try{for(int i=modules.Count-1;i>=0;i--)modules[i].EndSession();waves.Stop();driver.Reset();projectiles.Clear();items.ResetTransient();Begin(false);Publish(new PhaseChangedEvent{OldPhase=old,NewPhase=GamePhase.Build,DayIndex=1});r=Phase(GamePhase.DayEvent);if(r.State!=OperationState.Committed)return Reject(c,r.Error);r=dayEvents.EnsureEvent(1,request.Mode);if(r.State!=OperationState.Committed)return Reject(c,r.Error);SynchronizeDayEvent();return Finish(c,body,Success(c));}catch(Exception){End(DeathReason.SessionReset);core.Store.Reset();return Reject(c,ErrorCode.InternalFailure);}}
 public OperationResult TryLoadRun(CommandContext c,CheckpointData data){string body="load:"+Fingerprint(data);OperationResult r;if(!Check(c,body,out r))return r;if(GetSnapshot().Phase!=GamePhase.Menu&&GetSnapshot().Phase!=GamePhase.GameOver)return Reject(c,ErrorCode.WrongPhase);if(data==null)return Reject(c,ErrorCode.SaveCorrupt);if(data.SaveVersion!=1||data.ContractVersion!=ContractVersion.Value)return Reject(c,ErrorCode.SaveVersionUnsupported);if(data.ConfigVersion!=catalog.GetSettings().ConfigVersion)return Reject(c,ErrorCode.ConfigMismatch);if(data.DayEvent!=null&&!data.DayEvent.Resolved)return Reject(c,ErrorCode.EventUnresolved);if(data.SpringHp<=0||!Enum.IsDefined(typeof(GameMode),data.Mode)||(data.Mode==GameMode.Story&&data.DayIndex>catalog.GetSettings().StoryDays))return Reject(c,ErrorCode.SaveCorrupt);var valid=core.Store.ValidateCheckpoint(data);if(valid.Error!=ErrorCode.None)return Reject(c,valid.Error);var old=GetSnapshot().Phase;End(DeathReason.SessionReset);valid=core.Store.Restore(data);if(valid.Error!=ErrorCode.None)return Reject(c,valid.Error);var fileSave=saves as Spotlight.Core.Save.SaveService;if(fileSave!=null){valid=fileSave.RestoreHistoryFor(data);if(valid.Error!=ErrorCode.None)return Reject(c,valid.Error);}try{Begin(true);Publish(new PhaseChangedEvent{OldPhase=old,NewPhase=GamePhase.Build,DayIndex=data.DayIndex});return Finish(c,body,Success(c));}catch(Exception){End(DeathReason.SessionReset);core.Store.Reset();return Reject(c,ErrorCode.InternalFailure);}}
 public OperationResult TryStartNight(CommandContext c){const string body="start";OperationResult r;if(!Check(c,body,out r))return r;var f=GetSnapshot();if(f.Phase!=GamePhase.Build)return Reject(c,ErrorCode.WrongPhase);var e=core.Store.GetDayEventState();if(e!=null&&!e.Resolved)return Reject(c,ErrorCode.EventUnresolved);if(!SpringAlive()){Lose();return Reject(c,ErrorCode.TargetDead);}r=saves.SaveCheckpoint(core.Commands.Create(core.Transactions.Revision),SaveReason.BeforeNight);if(r.State!=OperationState.Committed)return Reject(c,r.Error);r=waves.StartNight(f.DayIndex,f.Mode);if(r.State!=OperationState.Committed)return Reject(c,r.Error);driver.Reset();projectiles.Clear();items.ResetTransient();skill.ResetForNight();towers.ResetNightCooldowns();r=Phase(GamePhase.Night);if(r.State!=OperationState.Committed){waves.Stop();return Reject(c,r.Error);}return Finish(c,body,Success(c));}
 public void Tick(TickContext c){if(c.Stage!=TickStage.Outcome||GetSnapshot().Phase!=GamePhase.Night)return;var w=waves.GetSnapshot();EvaluateNight(new NightOutcome{DayIndex=GetSnapshot().DayIndex,TickIndex=c.TickIndex,WavesComplete=w.Complete,FinalBossKilled=w.FinalBossKilled,SpringDestroyed=!SpringAlive()});}
 public void EvaluateNight(NightOutcome outcome){var f=GetSnapshot();if(outcome==null||f.Phase!=GamePhase.Night||outcome.DayIndex!=f.DayIndex)return;if(outcome.SpringDestroyed||!SpringAlive()){Lose();return;}if(damage.PendingCount>0)return;if(f.Mode==GameMode.Story&&f.DayIndex==catalog.GetSettings().StoryDays){if(outcome.FinalBossKilled){if(Phase(GamePhase.Ending).State!=OperationState.Committed)return;End(DeathReason.VictoryCleanup);Publish(new RunEndedEvent{Mode=f.Mode,Won=true,DayIndex=f.DayIndex});}return;}if(outcome.WavesComplete){waves.Stop();projectiles.Clear();items.ResetTransient();Phase(GamePhase.NightResult);}}
 void Lose(){var f=GetSnapshot();if(f.Phase==GamePhase.GameOver)return;if(Phase(GamePhase.GameOver).State!=OperationState.Committed)return;End(DeathReason.SessionReset);Publish(new RunEndedEvent{Mode=f.Mode,Won=false,DayIndex=f.DayIndex});}
 public void SynchronizeDayEvent(){if(synchronizing)return;synchronizing=true;try{var f=GetSnapshot();if(f.Phase!=GamePhase.DayEvent&&f.Phase!=GamePhase.Build)return;if(!SpringAlive()){Lose();return;}if(f.Phase==GamePhase.DayEvent){var e=core.Store.GetDayEventState();if(e==null||e.DayIndex!=f.DayIndex){var ensure=dayEvents.EnsureEvent(f.DayIndex,f.Mode);if(ensure.State!=OperationState.Committed)return;e=core.Store.GetDayEventState();}if(e!=null&&e.DayIndex==f.DayIndex&&e.Resolved){if(Phase(GamePhase.Build).State==OperationState.Committed)saves.SaveCheckpoint(core.Commands.Create(core.Transactions.Revision),SaveReason.DayReady);}}}finally{synchronizing=false;}}
 public OperationResult TryConfirmNightResult(CommandContext c){const string body="confirm";OperationResult r;if(!Check(c,body,out r))return r;var f=GetSnapshot();if(f.Phase!=GamePhase.NightResult)return Reject(c,ErrorCode.WrongPhase);var endless=catalog.GetEndlessDefinition();if(f.Mode==GameMode.Endless&&endless!=null&&f.DayIndex==endless.MilestoneNight&&!f.Milestone50Claimed)return Reject(c,ErrorCode.EventUnresolved);return Finish(c,body,Dawn(c));}
 OperationResult Dawn(CommandContext c){var f=GetSnapshot();ProductionResult p;var random=core.Random.GetState(RandomStream.Production);try{p=rules.ResolveProduction(new ProductionInput{SettlementId=f.RunId+":"+f.DayIndex,CompletedNight=f.DayIndex,Board=core.Board.GetSnapshot(),Random=random});}catch(Exception){return Reject(c,ErrorCode.InternalFailure);}if(p==null||p.ExpectedRevision!=f.Revision||p.CompletedNight!=f.DayIndex||p.NextRandom.Stream!=RandomStream.Production)return Reject(c,ErrorCode.InvalidDefinition);var progress=Patch(GamePhase.DawnSettlement);progress.LastSettledNight=f.DayIndex;progress.DayIndex=f.DayIndex+1;var r=core.Transactions.TryCommit(new StateMutationBatch{Context=core.Commands.Create(core.Transactions.Revision),Reason="dawn.settle",Board=p.Board,ResourceDeltas=p.HandDeltas,Random=new[]{new RandomStateWrite{Before=random,After=p.NextRandom}},Progress=progress});if(r.State!=OperationState.Committed)return Reject(c,r.Error);towers.SynchronizeBoard();Publish(new DawnSettledEvent{SettlementId=p.SettlementId,CompletedNight=f.DayIndex,Rewards=p.HandDeltas});r=Phase(GamePhase.DayEvent);if(r.State!=OperationState.Committed)return Reject(c,r.Error);r=dayEvents.EnsureEvent(progress.DayIndex,f.Mode);if(r.State!=OperationState.Committed)return Reject(c,r.Error);SynchronizeDayEvent();return Success(c);}
 public OperationResult TryContinueEndless(CommandContext c){const string body="continue";OperationResult r;if(!Check(c,body,out r))return r;var f=GetSnapshot();var d=catalog.GetEndlessDefinition();if(f.Mode!=GameMode.Endless||f.Phase!=GamePhase.NightResult||d==null||f.DayIndex!=d.MilestoneNight)return Reject(c,ErrorCode.WrongPhase);if(!f.Milestone50Claimed){var patch=Patch(GamePhase.NightResult);patch.Milestone50Claimed=true;r=core.Transactions.TryCommit(new StateMutationBatch{Context=core.Commands.Create(core.Transactions.Revision),Reason="endless.milestone",ResourceDeltas=d.MilestoneRewards,Progress=patch});if(r.State!=OperationState.Committed)return Reject(c,r.Error);Publish(new EndlessMilestoneEvent{NightIndex=f.DayIndex,Claimed=true});}return Finish(c,body,Dawn(c));}
 public OperationResult TryDismissTutorial(CommandContext c){const string body="tutorial";OperationResult r;if(!Check(c,body,out r))return r;var f=GetSnapshot();if(f.Phase!=GamePhase.Build)return Reject(c,ErrorCode.WrongPhase);if(!f.TutorialShown){var p=Patch(GamePhase.Build);p.TutorialShown=true;r=core.Transactions.TryCommit(new StateMutationBatch{Context=core.Commands.Create(core.Transactions.Revision),Reason="tutorial.dismiss",Progress=p});if(r.State!=OperationState.Committed)return Reject(c,r.Error);}saves.SaveCheckpoint(core.Commands.Create(core.Transactions.Revision),SaveReason.DeploymentChanged);return Finish(c,body,Success(c));}
 public OperationResult TryReturnToMenu(CommandContext c){const string body="menu";OperationResult r;if(!Check(c,body,out r))return r;var f=GetSnapshot();if(f.Phase==GamePhase.DawnSettlement)return Reject(c,ErrorCode.WrongPhase);if(f.Phase==GamePhase.Build){if(!SpringAlive()){Lose();f=GetSnapshot();}else{r=saves.SaveCheckpoint(core.Commands.Create(core.Transactions.Revision),SaveReason.Manual);if(r.State!=OperationState.Committed)return Reject(c,r.Error);}}End(DeathReason.SessionReset);core.Store.Reset();Publish(new PhaseChangedEvent{OldPhase=f.Phase,NewPhase=GamePhase.Menu,DayIndex=0});return Finish(c,body,Success(c));}
 static string Fingerprint(object value){var b=new System.Text.StringBuilder();Append(b,value);return b.ToString();}static void Append(System.Text.StringBuilder b,object v){if(v==null){b.Append("null;");return;}var t=v.GetType();if(t.IsPrimitive||t.IsEnum||v is string||v is Guid){var s=Convert.ToString(v,System.Globalization.CultureInfo.InvariantCulture);b.Append(s.Length).Append(':').Append(s).Append(';');return;}var list=v as System.Collections.IEnumerable;if(list!=null){b.Append('[');foreach(var x in list)Append(b,x);b.Append(']');return;}foreach(var field in t.GetFields())Append(b,field.GetValue(v));}
 void Publish<T>(T value)where T:class{if(events!=null)try{events.Publish(value);}catch(Exception){}}
}
}





