using System;
using System.Collections.Generic;
using Spotlight.Contracts;
namespace Spotlight.Core
{
    public sealed class DeploymentService : IDeploymentService
    {
        readonly SessionStateStore store;readonly IStateTransactionService transactions;
        public DeploymentService(SessionStateStore store,IStateTransactionService transactions){this.store=store;this.transactions=transactions;}
        ErrorCode CellCheck(CellCoord coord,OccupantKind kind,string id,bool ignoreOccupant){CellSnapshot c;if(!store.Cells.TryGetValue(coord,out c))return ErrorCode.OutOfBounds;if(c.Reserved)return ErrorCode.ReservedCell;if(!ignoreOccupant && c.OccupantKind!=OccupantKind.None)return ErrorCode.Occupied;TowerDefinition t;ElementDefinition e;bool blocks;if(kind==OccupantKind.Tower && store.Catalog.TryGetTower(id,out t))blocks=true;else if(kind==OccupantKind.ElementBlock && store.Catalog.TryGetElement(id,out e))blocks=e.BlocksGround;else return ErrorCode.InvalidDefinition;return blocks && c.OnGroundPath?ErrorCode.InvalidPathPlacement:ErrorCode.None;}
        ResourceAmount[] Cost(OccupantKind kind,string id){if(kind==OccupantKind.ElementBlock)return new ResourceAmount[] {new ResourceAmount(ResourceBucket.Hand,id,1)};TowerDefinition t;if(!store.Catalog.TryGetTower(id,out t))return new ResourceAmount[0];return t.BuildCost==null?new ResourceAmount[0]:new List<ResourceAmount>(t.BuildCost).ToArray();}
        public PlacementCheck CheckPlacement(PlacementRequest request){if(request==null)return new PlacementCheck {Error=ErrorCode.InvalidArgument,Cost=new ResourceAmount[0]};ResourceAmount[] cost=Cost(request.Kind,request.DefinitionId);ErrorCode e=store.Progress.Phase==GamePhase.Build?CellCheck(request.Cell,request.Kind,request.DefinitionId,false):ErrorCode.WrongPhase;if(e==ErrorCode.None && request.Kind==OccupantKind.Tower){TowerDefinition t;store.Catalog.TryGetTower(request.DefinitionId,out t);int count=0;foreach(CellSnapshot c in store.Cells.Values)if(c.OccupantKind==OccupantKind.Tower && c.DefinitionId==request.DefinitionId)count++;if(t.PlacementLimit>0 && count>=t.PlacementLimit)e=ErrorCode.LimitReached;}if(e==ErrorCode.None){Dictionary<string,long> sums=new Dictionary<string,long>();try{foreach(ResourceAmount r in cost){if(r.Amount<0){e=ErrorCode.InvalidDefinition;break;}string key=SessionStateStore.Key(r.Bucket,r.DefinitionId);long n;sums.TryGetValue(key,out n);sums[key]=checked(n+r.Amount);}foreach(var sum in sums){long n;store.Quantities.TryGetValue(sum.Key,out n);if(n<sum.Value)e=ErrorCode.InsufficientCost;}}catch(OverflowException){e=ErrorCode.InvalidDefinition;}}return new PlacementCheck {Error=e,Cell=request.Cell,Cost=cost};}
        OperationResult Reject(CommandContext context,ErrorCode error){return new OperationResult(OperationState.Rejected,error,context.CommandId,store.Progress.Revision,"deployment."+error.ToString());}
        StateMutationBatch Batch(CommandContext c,string reason){return new StateMutationBatch { Context=c,Reason=reason,Board=new BoardMutation[0],Actors=new ActorMutation[0],ResourceDeltas=new ResourceAmount[0],Random=new RandomStateWrite[0] };}
        public OperationResult TryPlace(CommandContext context,PlacementRequest request){ // Rebuild deterministic batch before state-based checks for successful retries.
            OperationResult prior;if(store.Results.TryGetValue(context.CommandId,out prior))return RetryPlace(context,request);
            PlacementCheck check=CheckPlacement(request);if(check.Error!=ErrorCode.None)return Reject(context,check.Error);long next=store.NextEntityId,sequence=store.NextSpawnSequence;if(next==long.MaxValue || sequence==long.MaxValue)return Reject(context,ErrorCode.InvalidArgument);EntityId id=new EntityId(next);StateMutationBatch batch=Batch(context,"deployment.place");batch.Board=new BoardMutation[] {new BoardMutation {Kind=BoardMutationKind.Place,EntityId=id,OccupantKind=request.Kind,DefinitionId=request.DefinitionId,To=request.Cell}};List<ResourceAmount> deltas=new List<ResourceAmount>();foreach(ResourceAmount r in check.Cost)deltas.Add(new ResourceAmount(r.Bucket,r.DefinitionId,-r.Amount));batch.ResourceDeltas=deltas.ToArray();if(request.Kind==OccupantKind.Tower){TowerDefinition t;store.Catalog.TryGetTower(request.DefinitionId,out t);ActorSnapshot actor=store.Tower(id,t,request.Cell);store.NextSpawnSequence=sequence;batch.Actors=new ActorMutation[] {new ActorMutation {Kind=ActorMutationKind.Register,ActorId=id,Registration=actor}};}OperationResult result=transactions.TryCommit(batch);if(result.State==OperationState.Committed){store.NextEntityId=checked(next+1);if(request.Kind==OccupantKind.Tower)store.NextSpawnSequence=checked(sequence+1);deploymentRequests[context.CommandId]=RequestKey("place",request.Kind,request.DefinitionId,request.Cell,new CellCoord());}return result;}
        Dictionary<Guid,string> deploymentRequests { get { return store.DeploymentRequests; } }
        static string RequestKey(string action,OccupantKind kind,string id,CellCoord a,CellCoord b){return action+":"+((int)kind)+":"+id+":"+a.X+","+a.Y+":"+b.X+","+b.Y;}
        OperationResult RetryPlace(CommandContext context,PlacementRequest request){if(request==null)return Reject(context,ErrorCode.DuplicateCommand);return Retry(context,RequestKey("place",request.Kind,request.DefinitionId,request.Cell,new CellCoord()));}
        OperationResult Retry(CommandContext context,string key){string saved;OperationResult prior;if(store.Results.TryGetValue(context.CommandId,out prior)){if(deploymentRequests.TryGetValue(context.CommandId,out saved) && saved==key && context.RunId==store.Progress.RunId)return prior;return Reject(context,ErrorCode.DuplicateCommand);}return Reject(context,ErrorCode.InternalFailure);}
        public OperationResult TryMove(CommandContext context,CellCoord from,CellCoord to){return Move(context,from,to,false);}
        public OperationResult TrySwap(CommandContext context,CellCoord a,CellCoord b){return Move(context,a,b,true);}
        OperationResult Move(CommandContext context,CellCoord from,CellCoord to,bool swap){string key=RequestKey(swap?"swap":"move",OccupantKind.None,null,from,to);if(store.Results.ContainsKey(context.CommandId))return Retry(context,key);if(store.Progress.Phase!=GamePhase.Build)return Reject(context,ErrorCode.WrongPhase);CellSnapshot a,b;if(!store.Cells.TryGetValue(from,out a) || !store.Cells.TryGetValue(to,out b))return Reject(context,ErrorCode.OutOfBounds);if(from.Equals(to))return Reject(context,ErrorCode.InvalidArgument);if(a.OccupantKind==OccupantKind.None || (swap && b.OccupantKind==OccupantKind.None))return Reject(context,ErrorCode.EmptyCell);ErrorCode e=CellCheck(to,a.OccupantKind,a.DefinitionId,swap);if(e==ErrorCode.None && swap)e=CellCheck(from,b.OccupantKind,b.DefinitionId,true);if(e!=ErrorCode.None)return Reject(context,e);List<BoardMutation> moves=new List<BoardMutation>();moves.Add(new BoardMutation {Kind=BoardMutationKind.Move,EntityId=a.OccupantId,OccupantKind=a.OccupantKind,DefinitionId=a.DefinitionId,From=from,To=to});if(swap)moves.Add(new BoardMutation {Kind=BoardMutationKind.Move,EntityId=b.OccupantId,OccupantKind=b.OccupantKind,DefinitionId=b.DefinitionId,From=to,To=from});StateMutationBatch batch=Batch(context,swap?"deployment.swap":"deployment.move");batch.Board=moves.ToArray();OperationResult result=transactions.TryCommit(batch);if(result.State==OperationState.Committed)deploymentRequests[context.CommandId]=key;return result;}
        public OperationResult TryRecall(CommandContext context,CellCoord cell){string key=RequestKey("recall",OccupantKind.None,null,cell,new CellCoord());if(store.Results.ContainsKey(context.CommandId))return Retry(context,key);if(store.Progress.Phase!=GamePhase.Build)return Reject(context,ErrorCode.WrongPhase);CellSnapshot c;if(!store.Cells.TryGetValue(cell,out c))return Reject(context,ErrorCode.OutOfBounds);if(c.OccupantKind==OccupantKind.None)return Reject(context,ErrorCode.EmptyCell);StateMutationBatch batch=Batch(context,"deployment.recall");batch.Board=new BoardMutation[] {new BoardMutation {Kind=BoardMutationKind.Remove,EntityId=c.OccupantId,OccupantKind=c.OccupantKind,DefinitionId=c.DefinitionId,From=cell}};if(c.OccupantKind==OccupantKind.ElementBlock)batch.ResourceDeltas=new ResourceAmount[] {new ResourceAmount(ResourceBucket.Hand,c.DefinitionId,1)};else{TowerDefinition t;if(!store.Catalog.TryGetTower(c.DefinitionId,out t))return Reject(context,ErrorCode.InvalidDefinition);batch.Actors=new ActorMutation[] {new ActorMutation {Kind=ActorMutationKind.Remove,ActorId=c.OccupantId}};List<ResourceAmount> refund=new List<ResourceAmount>();foreach(ResourceAmount r in Cost(c.OccupantKind,c.DefinitionId))refund.Add(new ResourceAmount(r.Bucket,r.DefinitionId,(long)Math.Floor(r.Amount*(double)t.RecallRefundRatio)));batch.ResourceDeltas=refund.ToArray();}OperationResult result=transactions.TryCommit(batch);if(result.State==OperationState.Committed)deploymentRequests[context.CommandId]=key;return result;}
    }
}

