using System;
using System.Collections.Generic;
using Spotlight.Contracts;
namespace Spotlight.Enemies {
public sealed class EnemyServices : ISessionModule,ITickSystem,IEnemyService,IWaveService,IBossService {
 readonly IGameCatalog catalog; readonly IBoardQuery board; readonly IWorldQuery world; readonly IWorldMotionWriter motion; readonly IStateTransactionService tx; readonly ICommandContextFactory commands; readonly IEntityIdService ids; readonly IRandomService random; readonly IStatusService status; readonly IDamageService damage; readonly IProjectileService projectiles; readonly IEffectService effects; readonly IEventBus events; readonly IGameClock clock;
 sealed class Runtime { public EntityId Id; public EnemyDefinition Def; public PathDefinition Path; public int Segment; public float Progress,Attack; public float Damage; public bool Summon; public Dictionary<string,float> Skills=new Dictionary<string,float>(); public LootResult Loot; public RandomState Before; public bool Counted=true; public DeathReason Reason=DeathReason.Killed; }
 sealed class Group { public EntityId Owner; public SpawnGroupDefinition Def; public int Left; public float Due; public bool Summon; }
 readonly Dictionary<EntityId,Runtime> actors=new Dictionary<EntityId,Runtime>(); readonly List<Group> groups=new List<Group>(); readonly HashSet<EntityId> bosses=new HashSet<EntityId>(); LevelDefinition level; SessionStartContext session; List<WaveDefinition> waves=new List<WaveDefinition>(); int wave,alive; float delay; bool running,bossKilled;
 public IEnemyService Enemies {get{return this;}} public IWaveService Waves {get{return this;}} public IBossService Boss {get{return this;}} public ILootService Loot {get;private set;} public IReadOnlyList<ITickSystem> TickSystems {get{return new ITickSystem[]{this};}} public ModuleId Module {get{return ModuleId.Enemies;}} public IReadOnlyList<TickStage> Stages {get{return new[]{TickStage.SpawnAndBoss,TickStage.Movement,TickStage.Attacks,TickStage.DeathAndLoot};}}
 public EnemyServices(IGameCatalog catalog,IBoardQuery board,IWorldQuery world,IWorldMotionWriter motion,IStateTransactionService tx,ICommandContextFactory commands,IEntityIdService ids,IRandomService random,IStatusService status,IDamageService damage,IProjectileService projectiles,IEffectService effects,IEventBus events,IGameClock clock){this.catalog=catalog;this.board=board;this.world=world;this.motion=motion;this.tx=tx;this.commands=commands;this.ids=ids;this.random=random;this.status=status;this.damage=damage;this.projectiles=projectiles;this.effects=effects;this.events=events;this.clock=clock;Loot=new LootService(catalog,random);}
 OperationResult Result(ErrorCode error){return new OperationResult(error==ErrorCode.None?OperationState.Committed:OperationState.Rejected,error,Guid.Empty,tx.Revision,null);}
 public void BeginSession(SessionStartContext context){EndSession();session=new SessionStartContext{RunId=context.RunId,Mode=context.Mode,LevelId=context.LevelId,DayIndex=context.DayIndex,SpringId=context.SpringId,IsLoad=context.IsLoad};if(!catalog.TryGetLevel(context.LevelId,out level))throw new InvalidOperationException("Unknown level");}
 public void EndSession(){Stop();actors.Clear();bosses.Clear();alive=0;session=null;level=null;}
 public OperationResult TrySpawn(EnemySpawnRequest request,out EntityId actor){actor=new EntityId();EnemyDefinition d; if(session==null||request==null||float.IsNaN(request.HpMultiplier)||float.IsInfinity(request.HpMultiplier)||float.IsNaN(request.DamageMultiplier)||float.IsInfinity(request.DamageMultiplier)||!catalog.TryGetEnemy(request.DefinitionId,out d)||!d.Enabled||request.HpMultiplier<=0||request.DamageMultiplier<0)return Result(ErrorCode.InvalidDefinition);
  PathDefinition path=null; foreach(var p in level.Paths)if(p.Id==request.PathId&&p.SpawnPointId==request.SpawnPointId&&p.Movement==d.Movement)path=p;
  if(path==null||path.Cells==null||path.Cells.Count==0)return Result(ErrorCode.InvalidPathPlacement);
  var id=ids.Allocate();float hp=d.MaxHp*request.HpMultiplier;var registration=new ActorSnapshot{Id=id,Kind=ActorKind.Enemy,DefinitionId=d.Id,Position=board.CellToWorld(path.Cells[0]),PreviousPosition=board.CellToWorld(path.Cells[0]),CurrentHp=hp,MaxHp=hp,PhysicalReduction=d.PhysicalReduction,ElementResistance=d.Resistance,CollisionRadius=d.CollisionRadiusInCells*level.CellSize,Targetable=true,SpawnSequence=ids.AllocateSpawnSequence()};
  var result=tx.TryCommit(new StateMutationBatch{Context=commands.Create(tx.Revision),Reason="enemy.spawn",Actors=new[]{new ActorMutation{Kind=ActorMutationKind.Register,ActorId=id,Registration=registration}}});
  if(result.State!=OperationState.Committed)return result; actors.Add(id,new Runtime{Id=id,Def=d,Path=path,Damage=d.PhysicalDamage*request.DamageMultiplier,Summon=request.IsSummon});alive++;actor=id;if(d.IsFinalBoss || (d.BossSkillIds!=null&&d.BossSkillIds.Count>0))RegisterBoss(id);return result;
 }
 public IReadOnlyList<EnemySnapshot> GetSnapshot(){var list=new List<EnemySnapshot>();foreach(var r in actors.Values)list.Add(new EnemySnapshot{ActorId=r.Id,DefinitionId=r.Def.Id,PathId=r.Path.Id,Movement=r.Def.Movement,PathSegment=r.Segment,SegmentProgress=r.Progress,IsSummon=r.Summon});list.Sort(delegate(EnemySnapshot a,EnemySnapshot b){return a.ActorId.Value.CompareTo(b.ActorId.Value);});return list.ToArray();}
 WaveSnapshot IWaveService.GetSnapshot(){return WaveState();}
 WaveSnapshot WaveState(){int pending=0,summons=0;foreach(var g in groups)if(g.Summon)summons+=g.Left;else pending+=g.Left;return new WaveSnapshot{DayIndex=session==null?0:session.DayIndex,WaveIndex=waves.Count==0?0:waves[Math.Max(0,Math.Min(wave-1,waves.Count-1))].WaveIndex,PendingSpawnCount=pending,PendingSummonCount=summons,AliveCount=alive,AllGroupsFinished=pending==0&&summons==0,Complete=running&&wave>=waves.Count&&pending==0&&summons==0&&alive==0,FinalBossKilled=bossKilled};}
 bool ValidGroup(SpawnGroupDefinition g){EnemyDefinition d;if(g==null||g.Count<0||g.SpawnIntervalSeconds<=0||float.IsNaN(g.SpawnIntervalSeconds)||float.IsInfinity(g.SpawnIntervalSeconds)||g.StartDelaySeconds<0||g.HpMultiplier<=0||g.DamageMultiplier<0||!catalog.TryGetEnemy(g.EnemyId,out d)||!d.Enabled)return false;foreach(var p in level.Paths)if(p.Id==g.PathId&&p.SpawnPointId==g.SpawnPointId&&p.Movement==d.Movement)return true;return false;} public OperationResult StartNight(int dayIndex,GameMode mode){if(session==null)return Result(ErrorCode.WrongRun);if(dayIndex<1||alive>0)return Result(ErrorCode.InvalidArgument);var definitions=catalog.GetWaves(dayIndex,mode);foreach(var definition in definitions){if(definition.DelayAfterPreviousWaveSeconds<0)return Result(ErrorCode.InvalidDefinition);if(definition.Groups!=null)foreach(var g in definition.Groups)if(!ValidGroup(g))return Result(ErrorCode.InvalidDefinition);}Stop();session.DayIndex=dayIndex;waves=new List<WaveDefinition>(definitions);waves.Sort(delegate(WaveDefinition a,WaveDefinition b){return a.WaveIndex.CompareTo(b.WaveIndex);});wave=0;delay=waves.Count==0?0:waves[0].DelayAfterPreviousWaveSeconds;running=true;bossKilled=false;return Result(ErrorCode.None);}
 void AddGroups(EntityId owner,IReadOnlyList<SpawnGroupDefinition> definitions,bool summon,float offset=0){if(definitions==null)return;foreach(var d in definitions)groups.Add(new Group{Owner=owner,Def=d,Left=d.Count,Due=d.StartDelaySeconds+offset,Summon=summon});}
 public OperationResult ScheduleSummons(EntityId owner,IReadOnlyList<SpawnGroupDefinition> definitions){ActorSnapshot a;if(!running||!world.TryGetActor(owner,out a)||a.CurrentHp<=0)return Result(ErrorCode.TargetDead);if(definitions!=null)foreach(var g in definitions)if(!ValidGroup(g))return Result(ErrorCode.InvalidDefinition);AddGroups(owner,definitions,true);return Result(ErrorCode.None);}
 public void CancelSummons(EntityId owner){groups.RemoveAll(delegate(Group g){return g.Summon&&g.Owner.Equals(owner);});}
 public void Stop(){running=false;groups.Clear();waves.Clear();wave=0;}
 public void RegisterBoss(EntityId actor){Runtime r;if(!actors.TryGetValue(actor,out r))return;bosses.Add(actor);if(r.Def.BossSkillIds!=null)foreach(string id in r.Def.BossSkillIds){BossSkillDefinition skill;if(catalog.TryGetBossSkill(id,out skill))r.Skills[id]=skill.FirstDelaySeconds;}}
 public void RemoveBoss(EntityId actor){bosses.Remove(actor);CancelSummons(actor);Runtime r;if(actors.TryGetValue(actor,out r))r.Skills.Clear();}
 public void Clear(){foreach(var id in new List<EntityId>(bosses))RemoveBoss(id);}
 public void DespawnAll(DeathReason reason){foreach(var r in new List<Runtime>(actors.Values)){r.Reason=reason;ResolveDeath(r,false);}}
 public void Tick(TickContext context){if(session==null||clock.GetSnapshot().IsPaused)return;float dt=Math.Max(0,context.DeltaSeconds);if(context.Stage==TickStage.SpawnAndBoss&&running){SpawnTick(dt);BossTick(dt);}if(running&&context.Stage==TickStage.Movement)foreach(var r in new List<Runtime>(actors.Values))Move(r,dt);if(running&&context.Stage==TickStage.Attacks)foreach(var r in new List<Runtime>(actors.Values))Attack(r,dt);if(context.Stage==TickStage.DeathAndLoot){var ordered=new List<Runtime>(actors.Values);ordered.Sort(delegate(Runtime a,Runtime b){return a.Id.Value.CompareTo(b.Id.Value);});foreach(var r in ordered){ActorSnapshot a;if(r.Reason!=DeathReason.Killed)ResolveDeath(r,false);else if(world.TryGetActor(r.Id,out a)&&a.CurrentHp<=0)ResolveDeath(r,true);if(r.Loot!=null && actors.ContainsKey(r.Id) && r.Counted)break;}events.Publish(new WaveChangedEvent{Snapshot=WaveState()});}}
 void SpawnTick(float dt){if(groups.Count==0&&alive==0&&wave<waves.Count){float wait=Math.Min(dt,Math.Max(0,delay));delay-=dt;if(delay<=0){AddGroups(new EntityId(),waves[wave].Groups,false,wait);wave++;delay=wave<waves.Count?waves[wave].DelayAfterPreviousWaveSeconds:0;}}
  foreach(var g in new List<Group>(groups)){if(g.Summon){ActorSnapshot owner;if(!world.TryGetActor(g.Owner,out owner)||owner.CurrentHp<=0||owner.DeathResolved){groups.Remove(g);continue;}}g.Due-=dt;while(g.Left>0&&g.Due<=0){float growth=g.Def.ApplyDayGrowth?1+.25f*(session.DayIndex-1):1;EntityId id;var result=TrySpawn(new EnemySpawnRequest{DefinitionId=g.Def.EnemyId,PathId=g.Def.PathId,SpawnPointId=g.Def.SpawnPointId,HpMultiplier=g.Def.HpMultiplier*growth,DamageMultiplier=g.Def.DamageMultiplier*growth,IsSummon=g.Summon},out id);if(result.State!=OperationState.Committed)break;g.Left--;g.Due+=g.Def.SpawnIntervalSeconds;}if(g.Left==0)groups.Remove(g);}}
 bool Living(Runtime r,out ActorSnapshot a){return world.TryGetActor(r.Id,out a)&&a.CurrentHp>0&&!a.DeathResolved;}
 bool InRange(Runtime r,ActorSnapshot a,ActorSnapshot spring){return Distance(a.Position,spring.Position)<=r.Def.RangeInCells*level.CellSize;}
 static float Distance(WorldPoint a,WorldPoint b){float x=a.X-b.X,y=a.Y-b.Y;return (float)Math.Sqrt(x*x+y*y);}
 void Move(Runtime r,float dt){ActorSnapshot a,spring;if(!Living(r,out a)||!world.TryGetActor(world.SpringId,out spring)||InRange(r,a,spring))return;var m=status.GetModifiers(r.Id);if(m.PreventMovement)return;float remaining=r.Def.SpeedInCellsPerSecond*level.CellSize*Math.Max(0,m.MoveMultiplier)*dt;WorldPoint position=a.Position;int segment=r.Segment;float progress=r.Progress;
  while(remaining>0&&segment<r.Path.Cells.Count-1){CellSnapshot nextCell;if(r.Def.Movement==MovementKind.Ground&&board.TryGetCell(r.Path.Cells[segment+1],out nextCell)&&nextCell.BlocksGround)break;var from=board.CellToWorld(r.Path.Cells[segment]);var to=board.CellToWorld(r.Path.Cells[segment+1]);float length=Distance(from,to);if(length<=0){segment++;progress=0;continue;}float travel=Math.Min(remaining,length-progress); WorldPoint current=new WorldPoint(from.X+(to.X-from.X)*progress/length,from.Y+(to.Y-from.Y)*progress/length); float ux=(to.X-from.X)/length,uy=(to.Y-from.Y)/length; float sx=current.X-spring.Position.X,sy=current.Y-spring.Position.Y; float radius=r.Def.RangeInCells*level.CellSize; float projection=sx*ux+sy*uy; float discriminant=projection*projection-(sx*sx+sy*sy-radius*radius); if(discriminant>=0){float entry=-projection-(float)Math.Sqrt(discriminant);if(entry>=0&&entry<=travel){travel=entry;remaining=travel;}} progress+=travel;remaining-=travel;position=new WorldPoint(from.X+(to.X-from.X)*progress/length,from.Y+(to.Y-from.Y)*progress/length);if(Distance(position,spring.Position)<=r.Def.RangeInCells*level.CellSize)remaining=0;if(progress>=length){segment++;progress=0;}}
  if(motion.TrySetPosition(r.Id,position).State==OperationState.Committed){r.Segment=segment;r.Progress=progress;}}
 void Attack(Runtime r,float dt){ActorSnapshot a,spring;if(!Living(r,out a)||!world.TryGetActor(world.SpringId,out spring)||spring.CurrentHp<=0)return;var m=status.GetModifiers(r.Id);if(m.PreventAttack)return;r.Attack-=dt*Math.Max(0,m.AttackRateMultiplier);if(!InRange(r,a,spring)){r.Attack=Math.Max(0,r.Attack);return;}while(r.Attack<=0){Fire(r,a,spring,r.Def.ProjectileId,r.Damage,DamageOrigin.Enemy);r.Attack+=Math.Max(.001f,r.Def.AttackIntervalSeconds);}}
 void Fire(Runtime r,ActorSnapshot a,ActorSnapshot spring,string projectile,float amount,DamageOrigin origin){if(!string.IsNullOrEmpty(projectile))projectiles.Spawn(new ProjectileSpawnRequest{Source=r.Id,InitialTarget=spring.Id,Origin=a.Position,AimPoint=spring.Position,DefinitionId=projectile,PhysicalDamage=amount,DamageOrigin=origin});else damage.Enqueue(new DamagePacket{PacketId=Guid.NewGuid().ToString("N"),Source=r.Id,Target=spring.Id,Origin=origin,PhysicalDamage=amount});}
 void BossTick(float dt){foreach(var id in new List<EntityId>(bosses)){Runtime r;ActorSnapshot a,spring;if(!actors.TryGetValue(id,out r)||!Living(r,out a)){RemoveBoss(id);continue;}foreach(var key in new List<string>(r.Skills.Keys)){BossSkillDefinition skill;if(!catalog.TryGetBossSkill(key,out skill)||skill.PeriodSeconds<=0)continue;r.Skills[key]-=dt;while(r.Skills[key]<=0){if(!string.IsNullOrEmpty(skill.ProjectileId)&&world.TryGetActor(world.SpringId,out spring))Fire(r,a,spring,skill.ProjectileId,skill.ProjectileDamage,DamageOrigin.Boss);if(skill.Summons!=null)ScheduleSummons(id,skill.Summons);if(skill.Effects!=null&&skill.Effects.Count>0)effects.TryExecute(new EffectBatchRequest{Context=commands.Create(tx.Revision),Source=id,Origin=DamageOrigin.Boss,Effects=skill.Effects});r.Skills[key]+=skill.PeriodSeconds;}}}}
 void ResolveDeath(Runtime r,bool killed){ActorSnapshot a;if(!world.TryGetActor(r.Id,out a)){if(r.Counted)alive=Math.Max(0,alive-1);RemoveBoss(r.Id);status.ClearTransient(r.Id);actors.Remove(r.Id);return;}bool reward=killed&&!a.DeathResolved&&r.Reason==DeathReason.Killed;
  if(reward){if(r.Loot==null){r.Before=random.GetState(RandomStream.Drop);r.Loot=Loot.Resolve(new LootInput{EnemyId=r.Id,DropTableId=r.Def.DropTableId,Random=r.Before});}var commit=tx.TryCommit(new StateMutationBatch{Context=commands.Create(tx.Revision),Reason="enemy.loot",ResourceDeltas=r.Loot.Rewards,Random=new[]{new RandomStateWrite{Before=r.Before,After=r.Loot.NextRandom}},Actors=new[]{new ActorMutation{Kind=ActorMutationKind.MarkDeathResolved,ActorId=r.Id}}});if(commit.State!=OperationState.Committed)return;events.Publish(new LootGrantedEvent{Enemy=r.Id,Rewards=r.Loot.Rewards});}
  if(r.Counted){alive=Math.Max(0,alive-1);r.Counted=false;if(killed&&r.Def.IsFinalBoss)bossKilled=true;RemoveBoss(r.Id);status.ClearTransient(r.Id);}
  var remove=tx.TryCommit(new StateMutationBatch{Context=commands.Create(tx.Revision),Reason="enemy.remove",Actors=new[]{new ActorMutation{Kind=ActorMutationKind.Remove,ActorId=r.Id}}});if(remove.State==OperationState.Committed){actors.Remove(r.Id);events.Publish(new ActorRemovedEvent{Actor=r.Id,Reason=r.Reason});}}
}
}





